#include "stdafx.h"
#include "TableGrid.h"
#include "../apputils.h"
#include "../utils/utils.h"

namespace FbeTable
{
long Grid::At(long row, long column) const { return row >= 0 && row < static_cast<long>(slots.size()) && column >= 0 && column < static_cast<long>(slots[row].size()) ? slots[row][column] : -1; }
void Grid::Ensure(long row, long column) { while (static_cast<long>(slots.size()) <= row) slots.push_back(std::vector<long>()); if (static_cast<long>(slots[row].size()) <= column) slots[row].resize(column + 1, -1); }

bool IsTableCell(const MSHTML::IHTMLElementPtr& element) { return (bool)element && (U::scmp(element->tagName, L"TD") == 0 || U::scmp(element->tagName, L"TH") == 0); }
MSHTML::IHTMLElementPtr FindTableElement(MSHTML::IHTMLElementPtr element) { while (element) { if (U::scmp(element->tagName, L"TABLE") == 0 && U::scmp(element->className, L"table") == 0) return element; element = element->parentElement; } return MSHTML::IHTMLElementPtr(); }
MSHTML::IHTMLElementPtr FindTableRow(MSHTML::IHTMLElementPtr element) { while (element) { if (U::scmp(element->tagName, L"TR") == 0 && U::scmp(element->className, L"tr") == 0) return element; element = element->parentElement; } return MSHTML::IHTMLElementPtr(); }
MSHTML::IHTMLElementPtr FindTableCell(MSHTML::IHTMLElementPtr element) { while (element) { if (IsTableCell(element)) return element; element = element->parentElement; } return MSHTML::IHTMLElementPtr(); }
void GetDirectCells(const MSHTML::IHTMLElementPtr& row, std::vector<MSHTML::IHTMLElementPtr>& cells) { cells.clear(); if (!row) return; for (MSHTML::IHTMLDOMNodePtr node(MSHTML::IHTMLDOMNodePtr(row)->firstChild); node; node = node->nextSibling) { if (node->nodeType != NODE_ELEMENT) continue; MSHTML::IHTMLElementPtr element(node); if (IsTableCell(element)) cells.push_back(element); } }
void GetCells(const MSHTML::IHTMLElementPtr& table, std::vector<MSHTML::IHTMLElementPtr>& cells) { cells.clear(); if (!table) return; MSHTML::IHTMLElementCollectionPtr rows(MSHTML::IHTMLElement2Ptr(table)->getElementsByTagName(L"TR")); if (!rows) return; for (long i = 0; i < rows->length; ++i) { std::vector<MSHTML::IHTMLElementPtr> rowCells; GetDirectCells(MSHTML::IHTMLElementPtr(rows->item(_variant_t(i), _variant_t())), rowCells); cells.insert(cells.end(), rowCells.begin(), rowCells.end()); } }
long GetSpan(const MSHTML::IHTMLElementPtr& cell, const wchar_t* fbName, const wchar_t* htmlName) { CString value(AU::GetAttrCS(cell, fbName)); if (value.IsEmpty()) value = AU::GetAttrCS(cell, htmlName); const long span = _wtol(value); return span > 0 ? span : 1; }
void SetSpan(const MSHTML::IHTMLElementPtr& cell, const wchar_t* fbName, const wchar_t* htmlName, long span) { if (span <= 1) { cell->removeAttribute(fbName, 0); cell->removeAttribute(htmlName, 0); } else { CString value; value.Format(L"%ld", span); const _variant_t attributeValue((const wchar_t*)value); cell->setAttribute(fbName, attributeValue, 0); cell->setAttribute(htmlName, attributeValue, 0); } }
static long g_buildCount = 0;
static bool Instrumented() { static const bool enabled = []() { wchar_t mode[4] = {}; return ::GetEnvironmentVariable(L"FBE_NEXT_TEST_MODE", mode, _countof(mode)) == 1 && mode[0] == L'1'; }(); return enabled; }
bool BuildGrid(const MSHTML::IHTMLElementPtr& table, Grid& grid) { if (Instrumented()) ++g_buildCount; if (!table) return false; MSHTML::IHTMLElementCollectionPtr tableRows(MSHTML::IHTMLElement2Ptr(table)->getElementsByTagName(L"TR")); if (!tableRows) return false; for (long rowIndex = 0; rowIndex < tableRows->length; ++rowIndex) { MSHTML::IHTMLElementPtr row(tableRows->item(_variant_t(rowIndex), _variant_t())); grid.rows.push_back(row); std::vector<MSHTML::IHTMLElementPtr> rowCells; GetDirectCells(row, rowCells); long column = 0; for (size_t i = 0; i < rowCells.size(); ++i) { grid.Ensure(rowIndex, column); while (grid.At(rowIndex, column) >= 0) { ++column; grid.Ensure(rowIndex, column); } LogicalCell cell = { rowCells[i], rowIndex, column, GetSpan(rowCells[i], L"fbcolspan", L"colspan"), GetSpan(rowCells[i], L"fbrowspan", L"rowspan") }; const long cellIndex = static_cast<long>(grid.cells.size()); grid.cells.push_back(cell); for (long r = rowIndex; r < rowIndex + cell.rowspan; ++r) for (long c = column; c < column + cell.colspan; ++c) { grid.Ensure(r, c); grid.slots[r][c] = cellIndex; } column += cell.colspan; } } for (size_t row = 0; row < grid.slots.size(); ++row) if (static_cast<long>(grid.slots[row].size()) > grid.columns) grid.columns = static_cast<long>(grid.slots[row].size()); return !grid.rows.empty(); }
long FindCell(const Grid& grid, const MSHTML::IHTMLElementPtr& element) { for (size_t i = 0; i < grid.cells.size(); ++i) if (grid.cells[i].element == element) return static_cast<long>(i); return -1; }
static bool Rectangle(const Grid& grid, long first, long last, std::vector<MSHTML::IHTMLElementPtr>& result) { if (first < 0 || last < 0) return false; const LogicalCell& a = grid.cells[first]; const LogicalCell& b = grid.cells[last]; const long rs = min(a.sourceRow, b.sourceRow), re = max(a.sourceRow + a.rowspan - 1, b.sourceRow + b.rowspan - 1), cs = min(a.startColumn, b.startColumn), ce = max(a.startColumn + a.colspan - 1, b.startColumn + b.colspan - 1); std::vector<bool> selected(grid.cells.size(), false); for (long r = rs; r <= re; ++r) for (long c = cs; c <= ce; ++c) { long owner = grid.At(r,c); if (owner >= 0) selected[owner] = true; } for (size_t i=0;i<grid.cells.size();++i) if(selected[i]) result.push_back(grid.cells[i].element); return !result.empty(); }
bool GetCellRectangle(const MSHTML::IHTMLElementPtr& firstCell, const MSHTML::IHTMLElementPtr& lastCell, std::vector<MSHTML::IHTMLElementPtr>& result) { result.clear(); MSHTML::IHTMLElementPtr table(FindTableElement(firstCell)); if (!table || table != FindTableElement(lastCell)) return false; Grid grid; return BuildGrid(table, grid) && Rectangle(grid, FindCell(grid, firstCell), FindCell(grid, lastCell), result); }
bool GetSelectedCells(MSHTML::IHTMLDocument2Ptr document, const MSHTML::IHTMLElementPtr& currentCell, std::vector<MSHTML::IHTMLElementPtr>& result) { result.clear(); MSHTML::IHTMLElementPtr anchor(FindTableCell(currentCell)); try { if (!anchor) { MSHTML::IHTMLTxtRangePtr range(document->selection->createRange()); if (range) { range->collapse(VARIANT_TRUE); anchor = FindTableCell(range->parentElement()); } } } catch (const _com_error&) {} MSHTML::IHTMLElementPtr table(FindTableElement(anchor)); Grid grid; if (!anchor || !table || !BuildGrid(table, grid)) return false; long first=FindCell(grid,anchor), last=first; try { MSHTML::IHTMLTxtRangePtr selection(document->selection->createRange()), start(selection ? selection->duplicate() : MSHTML::IHTMLTxtRangePtr()), end(selection ? selection->duplicate() : MSHTML::IHTMLTxtRangePtr()); if(start&&end) { start->collapse(VARIANT_TRUE); end->collapse(VARIANT_FALSE); long sf=FindCell(grid,FindTableCell(start->parentElement())), sl=FindCell(grid,FindTableCell(end->parentElement())); if(sf>=0&&sl>=0){first=sf;last=sl;} } } catch(const _com_error&) {} return Rectangle(grid,first,last,result); }
static unsigned long Hash(const CString& html) { unsigned long hash=2166136261u; for(int i=0;i<html.GetLength();++i){hash^=static_cast<unsigned long>(html[i]);hash*=16777619u;} return hash; }
CStringA BuildStructuralSnapshot(const Grid& grid) { CStringA snapshot; snapshot.Format("rows=%ld;columns=%ld;", static_cast<long>(grid.rows.size()), grid.columns); for(size_t i=0;i<grid.cells.size();++i) { const LogicalCell& cell=grid.cells[i]; CString id(AU::GetAttrCS(cell.element,L"id")),style,fbstyle(AU::GetAttrCS(cell.element,L"fbstyle")); MSHTML::IHTMLStylePtr runtimeStyle(cell.element ? cell.element->style : MSHTML::IHTMLStylePtr()); if(runtimeStyle) style=(const wchar_t*)_bstr_t(runtimeStyle->cssText); CString colspan(AU::GetAttrCS(cell.element,L"colspan")),fbcolspan(AU::GetAttrCS(cell.element,L"fbcolspan")),rowspan(AU::GetAttrCS(cell.element,L"rowspan")),fbrowspan(AU::GetAttrCS(cell.element,L"fbrowspan")),align(AU::GetAttrCS(cell.element,L"align")),fbalign(AU::GetAttrCS(cell.element,L"fbalign")),valign(AU::GetAttrCS(cell.element,L"valign")),fbvalign(AU::GetAttrCS(cell.element,L"fbvalign")); _bstr_t innerHtml(cell.element->innerHTML); CStringA entry; entry.Format("c%u:id=%S,tag=%S,row=%ld,column=%ld,logical-colspan=%ld,logical-rowspan=%ld,html=%08lX,style=%S,fbstyle=%S,colspan=%S,fbcolspan=%S,rowspan=%S,fbrowspan=%S,align=%S,fbalign=%S,valign=%S,fbvalign=%S;",static_cast<unsigned>(i),(const wchar_t*)id,(const wchar_t*)cell.element->tagName,cell.sourceRow,cell.startColumn,cell.colspan,cell.rowspan,Hash(CString((const wchar_t*)innerHtml)),(const wchar_t*)style,(const wchar_t*)fbstyle,(const wchar_t*)colspan,(const wchar_t*)fbcolspan,(const wchar_t*)rowspan,(const wchar_t*)fbrowspan,(const wchar_t*)align,(const wchar_t*)fbalign,(const wchar_t*)valign,(const wchar_t*)fbvalign); snapshot+=entry; } for(long r=0;r<static_cast<long>(grid.rows.size());++r) for(long c=0;c<grid.columns;++c){CStringA entry;entry.Format("s%ld,%ld=%ld;",r,c,grid.At(r,c));snapshot+=entry;} return snapshot; }
namespace GridDiagnostics { void ResetBuildCount() { if (Instrumented()) g_buildCount=0; } long BuildCount() { return Instrumented() ? g_buildCount : -1; } }
}
