import "oaidl.idl";
import "ocidl.idl";
import "..\contracts\fbe.idl";

[
	uuid(E75C3618-4D5A-4E53-A7E2-C00ED5975885),
]
library ExportDOCXLib
{
	importlib("stdole2.tlb");
	[
		uuid(09B5ABFF-177E-4C03-98D0-9EF4E1C9DB56)
	]
	coclass ExportDOCXPlugin
	{
		[default] interface IFBEExportPlugin;
	};
};
