#include <windows.h>
#include <oleauto.h>
#include <vector>
#include <iostream>
#include "../../src/fbe/FBE.h"
typedef HRESULT (WINAPI* CreateFixture)(int, IUnknown**);

class Progress : public IFBEProgressSink { LONG r = 1; public: bool called = false;
 STDMETHOD(QueryInterface)(REFIID i, void** p) { if (!p) return E_POINTER; *p = NULL; if (i != IID_IUnknown && i != IID_IFBEProgressSink) return E_NOINTERFACE; *p = this; AddRef(); return S_OK; } STDMETHOD_(ULONG,AddRef)(){return InterlockedIncrement(&r);} STDMETHOD_(ULONG,Release)(){LONG x=InterlockedDecrement(&r);if(!x)delete this;return x;} STDMETHOD(Report)(ULONG c,ULONG t,BSTR){called=(c==1&&t==1);return S_OK;} };
class Cancel : public IFBECancellationToken { LONG r=1; public: STDMETHOD(QueryInterface)(REFIID i,void**p){if(!p)return E_POINTER;*p=NULL;if(i!=IID_IUnknown&&i!=IID_IFBECancellationToken)return E_NOINTERFACE;*p=this;AddRef();return S_OK;} STDMETHOD_(ULONG,AddRef)(){return InterlockedIncrement(&r);} STDMETHOD_(ULONG,Release)(){LONG x=InterlockedDecrement(&r);if(!x)delete this;return x;} STDMETHOD(IsCancellationRequested)(BOOL* x){if(!x)return E_POINTER;*x=FALSE;return S_OK;} };
class Host : public IFBEPluginHost { LONG r=1; Progress* p; Cancel* c; public: Host():p(new Progress),c(new Cancel){} ~Host(){p->Release();c->Release();} bool progressed(){return p->called;}
 STDMETHOD(QueryInterface)(REFIID i,void**x){if(!x)return E_POINTER;*x=NULL;if(i!=IID_IUnknown&&i!=IID_IFBEPluginHost)return E_NOINTERFACE;*x=this;AddRef();return S_OK;} STDMETHOD_(ULONG,AddRef)(){return InterlockedIncrement(&r);} STDMETHOD_(ULONG,Release)(){LONG x=InterlockedDecrement(&r);if(!x)delete this;return x;}
 STDMETHOD(GetHostVersion)(BSTR*x){if(!x)return E_POINTER;*x=SysAllocString(L"test-version");return S_OK;} STDMETHOD(GetUiLocale)(BSTR*x){if(!x)return E_POINTER;*x=SysAllocString(L"ru-RU");return S_OK;} STDMETHOD(GetOwnerWindow)(LONGLONG*x){if(!x)return E_POINTER;*x=0x12345678LL;return S_OK;} STDMETHOD(GetProgressSink)(IFBEProgressSink**x){if(!x)return E_POINTER;*x=p;p->AddRef();return S_OK;} STDMETHOD(GetCancellationToken)(IFBECancellationToken**x){if(!x)return E_POINTER;*x=c;c->AddRef();return S_OK;} STDMETHOD(ReportMessage)(LONG,BSTR,BSTR){return S_OK;} STDMETHOD(Trace)(BSTR,BSTR){return S_OK;} };
class Snapshot : public IFBEDocumentSnapshot { LONG r=1; public:
 STDMETHOD(QueryInterface)(REFIID i,void**x){if(!x)return E_POINTER;*x=NULL;if(i!=IID_IUnknown&&i!=IID_IFBEDocumentSnapshot)return E_NOINTERFACE;*x=this;AddRef();return S_OK;} STDMETHOD_(ULONG,AddRef)(){return InterlockedIncrement(&r);} STDMETHOD_(ULONG,Release)(){LONG x=InterlockedDecrement(&r);if(!x)delete this;return x;}
 STDMETHOD(OpenXmlStream)(IStream**x){if(!x)return E_POINTER;*x=NULL;IStream*s=NULL;HRESULT h=CreateStreamOnHGlobal(NULL,TRUE,&s);if(FAILED(h))return h;const char v[]="<?xml version=\"1.0\" encoding=\"utf-8\"?><FictionBook>Привет</FictionBook>";ULONG n=0;h=s->Write(v,sizeof(v)-1,&n);LARGE_INTEGER z={};s->Seek(z,STREAM_SEEK_SET,NULL);*x=s;return h;} STDMETHOD(GetSourceFilePath)(BSTR*x){if(!x)return E_POINTER;*x=SysAllocString(L"C:\\test.fb2");return S_OK;} STDMETHOD(GetEncoding)(BSTR*x){if(!x)return E_POINTER;*x=SysAllocString(L"utf-8");return S_OK;} };
static int Fail(const wchar_t* what,HRESULT h){std::wcerr<<what<<L" 0x"<<std::hex<<h<<L"\n";return 1;}
int wmain(int argc,wchar_t**argv){if(argc!=2)return 2;HMODULE m=LoadLibraryW(argv[1]);if(!m)return 3;CreateFixture create=(CreateFixture)GetProcAddress(m,"CreateFbePluginV2Fixture");if(!create)create=(CreateFixture)GetProcAddress(m,"_CreateFbePluginV2Fixture@8");if(!create)return 4;
 for(int mode=0;mode<6;++mode){IUnknown*u=NULL;HRESULT h=create(mode,&u);if(FAILED(h))return Fail(L"create",h);IFBEPluginInfo2*i=NULL;h=u->QueryInterface(IID_IFBEPluginInfo2,(void**)&i);
  if(mode==1){if(h!=E_NOINTERFACE)return Fail(L"no-info",h);u->Release();continue;} if(mode==5){if(h!=E_FAIL)return Fail(L"qi-error",h);u->Release();continue;} if(FAILED(h))return Fail(L"info",h);BSTR id=NULL;ULONG api=0;i->GetPluginId(&id);i->GetApiVersion(&api);
  if(mode==3||mode==4){if((mode==3&&wcscmp(id,L"synthetic-v2")==0)||(mode==4&&api==2))return Fail(L"mismatch",E_FAIL);SysFreeString(id);i->Release();u->Release();continue;} SysFreeString(id);i->Release();IFBEExportPlugin2*e=NULL;h=u->QueryInterface(IID_IFBEExportPlugin2,(void**)&e);if(mode==2){if(h!=E_NOINTERFACE)return Fail(L"no-export",h);u->Release();continue;} if(FAILED(h))return Fail(L"export-qi",h);Host*host=new Host;Snapshot*snap=new Snapshot;h=e->Export(host,SysAllocString(L"test"),snap);bool p=host->progressed();snap->Release();host->Release();e->Release();u->Release();if(FAILED(h)||!p)return Fail(L"export",h);}
 FreeLibrary(m);std::wcout<<L"Plugin API v2 ABI fixture passed\n";return 0; }
