param([string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path)
$ErrorActionPreference='Stop'
function Text($p) { Get-Content -Raw -LiteralPath (Join-Path $RepoRoot $p) }
function Must($t,$p,$n) { if($t -notmatch $p){throw "Missing management contract: $n"} }
$frame=Text 'src\fbe\mainfrm.cpp'; $dialog=Text 'src\fbe\ScriptToolbarManagerDlg.cpp'; $manager=Text 'src\fbe\toolbars\ScriptToolbarManager.cpp'; $collection=Text 'src\fbe\toolbars\ScriptToolbarCollection.cpp'; $resource=Text 'src\fbe\resource.h'; $rc=Text 'src\fbe\FBE.rc'; $menuLocalization=Text 'localization\app-ui\fbe-idr-mainframe-menu.json'; $localization=Text 'localization\app-ui\fbe-small-dialogs.json'
Must $frame 'PortableToolbarStore::Load\(persistedToolbars\)' 'installed and portable definitions load through settings directory'
Must $frame 'if\(runtime\.window == NULL\) continue;' 'empty custom toolbar reaches layout adapter'
Must $frame 'ToolbarLayoutAdapter::Apply\(runtime\.window, items, catalog\)' 'UID layout is applied to every runtime control'
Must $frame 'DestroyScriptToolbarRuntimeControls' 'runtime controls have an explicit lifecycle owner'
Must $frame 'm_rebar\.DeleteBand\(band\)' 'runtime lifecycle deletes rebar bands before HWND destruction'
Must $frame 'MergeUnavailableScriptToolbarItems' 'temporarily missing scripts preserve their original layout slots'
Must $frame 'RefreshScriptToolbarViewMenu' 'View menu is rebuilt from script toolbar definitions'
Must $frame 'ID_VIEW_SCRIPT_TOOLBAR_DYNAMIC_FIRST' 'dynamic View menu commands are routed without fixed toolbar names'
Must $resource '#define ID_VIEW_SCRIPT_TOOLBAR_DYNAMIC_LAST\s+57599' 'dynamic View menu commands stop before standard WTL edit commands'
Must $frame 'static_assert\(ID_VIEW_SCRIPT_TOOLBAR_DYNAMIC_LAST < ID_EDIT_FIND' 'compile-time guard prevents Find command interception'
Must $frame 'ID_VIEW_SCRIPT_TOOLBARS_MANAGE, L"fbe\.menu\.idr_mainframe\.view\.script_toolbar_manager"' 'script-toolbar management command uses runtime localization'
Must $rc 'MENUITEM "Manage script toolbars\.\.\."' 'resource template stays ASCII-safe'
Must $menuLocalization 'fbe\.menu\.idr_mainframe\.view\.script_toolbar_manager' 'script-toolbar management menu has a localization key'
Must $frame 'ApplyScriptToolbarDefinitions\(previous, current\)' 'visibility changes use the same transactional persistence path'
Must $frame 'bool CMainFrame::ApplyScriptToolbarRuntimeDelta\(' 'runtime changes are isolated from persistence'
Must $frame 'ApplyScriptToolbarRuntimeDelta\(previous, current\)' 'management applies an in-memory runtime delta'
if($frame -match 'bool CMainFrame::ApplyScriptToolbarRuntimeDelta\([\s\S]*?\n\}') { if($Matches[0] -match 'PortableToolbarStore::') { throw 'Runtime delta must not read or write Toolbars.xml.' } }
if($frame -match 'bool CMainFrame::ApplyScriptToolbarDefinitions\([\s\S]*?\n\}') { if($Matches[0] -match 'if\(InitializeScripts\(\)\) return true') { throw 'Normal toolbar management must not run full script initialization.' } }
Must $frame 'CreateScriptToolbarRuntime' 'new visible custom toolbar uses a narrow runtime creator'
Must $frame 'DestroyScriptToolbarRuntime' 'removed or hidden custom toolbar owns its narrow destruction'
Must $frame 'm_rebar\.ShowBand\(band, visible\)' 'scripts-main visibility uses its existing rebar band'
Must $frame 'band != insertion && !m_rebar\.MoveBand\(band, insertion\)' 'reorder accepts a band already occupying its target position'
Must $dialog 'm_manager\.Create' 'create panel action'
Must $dialog 'NextDefaultPanelName\(\)' 'create uses a generated display name rather than edit-control input'
Must $dialog 'FbeLoadRuntimeStringByKey\(L"fbe\.script_toolbar_manager\.default_name"\)' 'generated display name uses runtime localization'
Must $dialog 'Commit\(createdId\)' 'created panel is selected after the incremental commit'
Must $dialog 'EM_SETSEL,0,-1' 'created name is selected for immediate rename'
if($dialog -match 'LRESULT CScriptToolbarManagerDlg::OnCreatePanel[\s\S]*?\n(?=LRESULT)') { if($Matches[0] -match 'GetDlgItemText') { throw 'Create must not consume stale text from the name edit control.' } }
Must $dialog 'm_manager\.Delete' 'delete panel action'
Must $dialog 'm_manager\.Rename' 'rename panel action'
Must $dialog 'm_manager\.SetVisible' 'visibility action'
Must $collection 'if\(id == L"scripts-main"\) return false' 'main panel cannot be deleted'
Must $collection 'CString ScriptToolbarCollection::NextDefaultName' 'display-name allocation is separate from internal NextId'
Must $collection 'm_items\[index\]\.id != L"scripts-main"' 'main Scripts toolbar does not reserve generated display-name numbers'
Must $collection 'name\.CompareNoCase\(candidate\)' 'generated names are checked case-insensitively'
Must $localization 'fbe\.script_toolbar_manager\.default_name' 'default panel-name localization key exists'
foreach($language in @('en-US','ru-RU','uk-UA','de-DE','fr-FR','es-ES','it-IT','pl-PL','pt-PT','nl-NL','cs-CZ','bg-BG')) { if($localization -notmatch ('"' + [regex]::Escape($language) + '"\s*:\s*"[^"\r\n]*%u')) { throw "Default panel-name localization lacks a numbered $language translation." } }
Must $manager 'definition->visible = visible' 'visibility persists in definition'
Must $dialog 'm_changed\(m_lastCommitted, m_manager\.Collection\(\)\.Items\(\)\)' 'dialog supplies pre-change state for rollback'
Write-Host 'Script toolbar management contract passed.'
