param([string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path)
$ErrorActionPreference='Stop'
function Text($p) { Get-Content -Raw -LiteralPath (Join-Path $RepoRoot $p) }
function Must($t,$p,$n) { if($t -notmatch $p){throw "Missing management contract: $n"} }
$frame=Text 'src\fbe\mainfrm.cpp'; $dialog=Text 'src\fbe\ScriptToolbarManagerDlg.cpp'; $manager=Text 'src\fbe\toolbars\ScriptToolbarManager.cpp'; $collection=Text 'src\fbe\toolbars\ScriptToolbarCollection.cpp'; $resource=Text 'src\fbe\resource.h'; $rc=Text 'src\fbe\FBE.rc'; $menuLocalization=Text 'localization\app-ui\fbe-idr-mainframe-menu.json'
Must $frame 'PortableToolbarStore::Load\(persistedToolbars\)' 'installed and portable definitions load through settings directory'
Must $frame 'if\(runtime\.window == NULL\) continue;' 'empty custom toolbar reaches layout adapter'
Must $frame 'ToolbarLayoutAdapter::Apply\(runtime\.window, items, catalog\)' 'UID layout is applied to every runtime control'
Must $frame 'DestroyScriptToolbarRuntimeControls' 'runtime controls have an explicit lifecycle owner'
Must $frame 'm_rebar\.DeleteBand\(band\)' 'runtime lifecycle deletes rebar bands before HWND destruction'
Must $frame 'MergeUnavailableScriptToolbarItems' 'temporarily missing scripts preserve their original layout slots'
Must $frame 'RefreshScriptToolbarViewMenu' 'View menu is rebuilt from script toolbar definitions'
Must $frame 'ID_VIEW_SCRIPT_TOOLBAR_DYNAMIC_FIRST' 'dynamic View menu commands are routed without fixed toolbar names'
Must $resource '#define ID_VIEW_SCRIPT_TOOLBAR_DYNAMIC_LAST\s+57599' 'dynamic View menu commands stop before standard WTL edit commands'
Must $frame 'static_assert\(ID_VIEW_SCRIPT_TOOLBAR_DYNAMIC_LAST < ID_EDIT_FIND' 'compile-time guard prevents Find command interception'
Must $frame 'ID_VIEW_SCRIPT_TOOLBARS_MANAGE, L"fbe\.menu\.idr_mainframe\.view\.script_toolbar_manager"' 'script-toolbar management command uses runtime localization'
Must $rc 'MENUITEM "Manage script toolbars\.\.\."' 'resource template stays ASCII-safe'
Must $menuLocalization 'fbe\.menu\.idr_mainframe\.view\.script_toolbar_manager' 'script-toolbar management menu has a localization key'
Must $frame 'ApplyScriptToolbarDefinitions\(previous, current\)' 'visibility changes use the same transactional persistence path'
Must $dialog 'm_manager\.Create' 'create panel action'
Must $dialog 'm_manager\.Delete' 'delete panel action'
Must $dialog 'm_manager\.Rename' 'rename panel action'
Must $dialog 'm_manager\.SetVisible' 'visibility action'
Must $collection 'if\(id == L"scripts-main"\) return false' 'main panel cannot be deleted'
Must $manager 'definition->visible = visible' 'visibility persists in definition'
Must $dialog 'm_changed\(m_lastCommitted, m_manager\.Collection\(\)\.Items\(\)\)' 'dialog supplies pre-change state for rollback'
Write-Host 'Script toolbar management contract passed.'
