<# Ensures package export uses the most recent saved trace when tracing is disabled. #>
[CmdletBinding()]
param([string]$Configuration = 'Release')
$ErrorActionPreference='Stop'; $root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path; $exe=Join-Path $root "out\$Configuration\FBE.exe"; $dir=Join-Path $env:LOCALAPPDATA 'FBE Next\Diagnostics'
if(!(Test-Path $exe)){throw 'FBE.exe missing'}; if(!(Get-ChildItem $dir -Filter 'fbe-trace-*.log' -ErrorAction SilentlyContinue)){throw 'A saved trace is required; run the active diagnostic package test first.'}
Add-Type @"
using System; using System.Runtime.InteropServices; public static class FbeSavedPackageWindow { public delegate bool P(IntPtr h,IntPtr x); [DllImport("user32.dll")] public static extern bool EnumWindows(P p,IntPtr x); [DllImport("user32.dll")] public static extern bool IsWindowVisible(IntPtr h); [DllImport("user32.dll")] public static extern uint GetWindowThreadProcessId(IntPtr h,out uint p); [DllImport("user32.dll")] public static extern int GetWindowTextLength(IntPtr h); [DllImport("user32.dll")] public static extern bool PostMessage(IntPtr h,uint m,IntPtr w,IntPtr l); public static IntPtr Find(int pid){IntPtr r=IntPtr.Zero;EnumWindows((h,x)=>{uint p;GetWindowThreadProcessId(h,out p);if(p==(uint)pid&&IsWindowVisible(h)&&GetWindowTextLength(h)>0){r=h;return false;}return true;},IntPtr.Zero);return r;} public static void Confirm(int pid){EnumWindows((h,x)=>{uint p;GetWindowThreadProcessId(h,out p);if(p==(uint)pid&&IsWindowVisible(h))PostMessage(h,0x0111,(IntPtr)6,IntPtr.Zero);return true;},IntPtr.Zero);} }
"@
$registry='HKCU:\Software\FBETeam\FictionBook Editor Next\Diagnostics';$flag='TraceNextLaunch';$saved=Get-ItemProperty -LiteralPath $registry -Name $flag -ErrorAction SilentlyContinue;$had=$null-ne$saved;$old=$env:FBE_NEXT_TRACE;$before=@(Get-ChildItem $dir -Filter 'FBE-Diagnostics-*.zip' -ErrorAction SilentlyContinue|% FullName);$p=$null
try {New-Item -Path $registry -Force|Out-Null;New-ItemProperty -LiteralPath $registry -Name $flag -PropertyType DWord -Value 0 -Force|Out-Null;$env:FBE_NEXT_TRACE='0';$p=Start-Process $exe -WorkingDirectory (Split-Path $exe) -PassThru;$limit=(Get-Date).AddSeconds(40);do{Start-Sleep -Milliseconds 200;$h=[FbeSavedPackageWindow]::Find($p.Id)}while($h-eq[IntPtr]::Zero-and(Get-Date)-lt$limit);if($h-eq[IntPtr]::Zero){throw 'FBE main window not found'};[FbeSavedPackageWindow]::PostMessage($h,0x111,[IntPtr]32916,[IntPtr]::Zero)|Out-Null;$limit=(Get-Date).AddSeconds(5);do{[FbeSavedPackageWindow]::Confirm($p.Id);Start-Sleep -Milliseconds 200;$zip=Get-ChildItem $dir -Filter 'FBE-Diagnostics-*.zip'|?{$before-notcontains$_.FullName}|Sort LastWriteTime -Desc|Select -First 1}while(!$zip-and(Get-Date)-lt$limit);if(!$zip){throw 'Package was not created with tracing disabled'};Add-Type -AssemblyName System.IO.Compression.FileSystem;$a=[IO.Compression.ZipFile]::OpenRead($zip.FullName);try{if(!($a.Entries.FullName|?{$_-like'trace/*'})){throw 'Saved-session package has no trace entries'}}finally{$a.Dispose()};Write-Host "Saved-session diagnostic package test passed: $($zip.FullName)"}finally{if($p-and!$p.HasExited){Stop-Process $p.Id -Force};$env:FBE_NEXT_TRACE=$old;Remove-ItemProperty -LiteralPath $registry -Name $flag -ErrorAction SilentlyContinue;if($had){New-ItemProperty -LiteralPath $registry -Name $flag -PropertyType DWord -Value([int]$saved.$flag)-Force|Out-Null}}
