[CmdletBinding()]
param([string]$Configuration = 'Release')
$ErrorActionPreference = 'Stop'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path; $exe=Join-Path $root "out\$Configuration\FBE.exe"; if(!(Test-Path $exe)){throw 'FBE.exe missing'}
Add-Type @"
using System; using System.Runtime.InteropServices;
public static class FbePackageWindow { public delegate bool P(IntPtr h,IntPtr x); [DllImport("user32.dll")] public static extern bool EnumWindows(P p,IntPtr x); [DllImport("user32.dll")] public static extern bool IsWindowVisible(IntPtr h); [DllImport("user32.dll")] public static extern uint GetWindowThreadProcessId(IntPtr h,out uint p); [DllImport("user32.dll")] public static extern int GetWindowTextLength(IntPtr h); [DllImport("user32.dll")] public static extern bool PostMessage(IntPtr h,uint m,IntPtr w,IntPtr l); public static IntPtr Find(int pid){IntPtr r=IntPtr.Zero; EnumWindows((h,x)=>{uint p;GetWindowThreadProcessId(h,out p);if(p==(uint)pid&&IsWindowVisible(h)&&GetWindowTextLength(h)>0){r=h;return false;}return true;},IntPtr.Zero);return r;} public static void Confirm(int pid){EnumWindows((h,x)=>{uint p;GetWindowThreadProcessId(h,out p);if(p==(uint)pid&&IsWindowVisible(h))PostMessage(h,0x0111,(IntPtr)6,IntPtr.Zero);return true;},IntPtr.Zero);} }
"@
$dir=Join-Path $env:LOCALAPPDATA 'FBE Next\Diagnostics'; $before=@(Get-ChildItem $dir -Filter 'FBE-Diagnostics-*.zip' -ErrorAction SilentlyContinue | % FullName)
$registry='HKCU:\Software\FBETeam\FictionBook Editor Next\Diagnostics'; $flag='TraceNextLaunch'; $saved=Get-ItemProperty -LiteralPath $registry -Name $flag -ErrorAction SilentlyContinue; $hadSaved=$null -ne $saved; if($hadSaved){Remove-ItemProperty -LiteralPath $registry -Name $flag}; $old=$env:FBE_NEXT_TRACE; $neighbors=@(); try { $env:FBE_NEXT_TRACE='1'; $p=Start-Process $exe -WorkingDirectory (Split-Path $exe) -PassThru; $limit=(Get-Date).AddSeconds(40); do{Start-Sleep -Milliseconds 250;$h=[FbePackageWindow]::Find($p.Id);$current=Get-ChildItem $dir -Filter ("fbe-trace-*-pid{0}*.log" -f $p.Id) -ErrorAction SilentlyContinue | Sort LastWriteTime -Desc | Select -First 1}while(($h -eq [IntPtr]::Zero -or !$current) -and (Get-Date)-lt $limit); if($h -eq [IntPtr]::Zero -or !$current){throw 'Current FBE trace or main window not found'}; $stem=$current.BaseName -replace '-part\d+$',''; $neighbors=@((Join-Path $dir ($stem+'-1.log')),(Join-Path $dir ($stem+'-1-part10.log'))); foreach($neighbor in $neighbors){[IO.File]::WriteAllText($neighbor,'safe neighboring diagnostic fixture',[Text.Encoding]::UTF8)}; [FbePackageWindow]::PostMessage($h,0x111,[IntPtr]32916,[IntPtr]::Zero)|Out-Null; $deadline=(Get-Date).AddSeconds(5); do{[FbePackageWindow]::Confirm($p.Id);Start-Sleep -Milliseconds 200;$zip=Get-ChildItem $dir -Filter 'FBE-Diagnostics-*.zip' | ? {$before -notcontains $_.FullName} | Sort LastWriteTime -Desc | Select -First 1}while(!$zip -and (Get-Date)-lt $deadline); if(!$zip){throw 'Diagnostic package not created'}; Add-Type -AssemblyName System.IO.Compression.FileSystem; $a=[IO.Compression.ZipFile]::OpenRead($zip.FullName); try { foreach($n in 'package-manifest.txt','environment-report.txt','fbelib-report.txt','diagnostic-modules.txt'){if(!$a.Entries.FullName.Contains($n)){throw "Missing ZIP entry $n"}}; if(!($a.Entries.FullName | ? {$_ -like 'trace/*'})){throw 'ZIP has no trace entries'}; foreach($neighbor in $neighbors){if($a.Entries.FullName -contains ('trace/'+[IO.Path]::GetFileName($neighbor))){throw "ZIP captured neighboring session: $neighbor"}}; foreach($entry in $a.Entries){$stream=$entry.Open();try{$buffer=New-Object byte[] 8192;while($stream.Read($buffer,0,$buffer.Length)-gt 0){}}finally{$stream.Dispose()}} } finally {$a.Dispose()}; Write-Host "Diagnostic package behavioral test passed: $($zip.FullName)" } finally {if($p -and !$p.HasExited){Stop-Process $p.Id -Force};foreach($neighbor in $neighbors){Remove-Item -LiteralPath $neighbor -Force -ErrorAction SilentlyContinue};$env:FBE_NEXT_TRACE=$old;if($hadSaved){New-Item -Path $registry -Force|Out-Null;New-ItemProperty -LiteralPath $registry -Name $flag -PropertyType DWord -Value ([int]$saved.$flag) -Force|Out-Null}}
