import "oaidl.idl";
import "ocidl.idl";
import "..\fbe\fbe.idl";

[
	uuid(B963BA28-01AA-40C2-8EF7-9F89D47C2F66),
]
library ExportHTMLLib
{
	importlib("stdole2.tlb");
	[
		uuid(C3098839-EF69-4DE5-B27D-1E80051CA843)
	]
	coclass ExportHTMLPlugin
	{
		[default] interface IFBEExportPlugin;
	};
};
