import "oaidl.idl";
import "ocidl.idl";
import "..\fbe\fbe.idl";

[
    uuid(F63062F5-AF65-4FB8-B692-054B71DD57FE),
]
library ExportEPUBLib
{
    importlib("stdole2.tlb");
    [
        uuid(36FCFB2D-C3D8-4B81-ABC1-5A09CA846515)
    ]
    coclass ExportEPUBPlugin
    {
        [default] interface IFBEExportPlugin;
    };
};
