#include "stdafx.h"
#include "ToolbarFactory.h"
#include "..\\StartupTrace.h"
#include "..\\UiMetrics.h"
namespace { struct ToolbarResourceData { WORD version; WORD width; WORD height; WORD itemCount; WORD* Items() { return reinterpret_cast<WORD*>(this + 1); } }; BOOL CALLBACK SetDialogFontForToolbarChild(HWND window, LPARAM) { ::SendMessage(window, WM_SETFONT, reinterpret_cast<WPARAM>(UiMetrics::DialogFont()), TRUE); return TRUE; } bool CopyToolbarImages(HIMAGELIST destination, HIMAGELIST source, int imageCount) { for(int index = 0; index < imageCount; ++index) { HICON icon = ::ImageList_GetIcon(source, index, ILD_NORMAL); const int copiedIndex = icon != NULL ? ::ImageList_AddIcon(destination, icon) : -1; if(icon != NULL) ::DestroyIcon(icon); if(copiedIndex != index) return false; } return true; } }
bool ToolbarFactory::ImageListHasMaskPlane(HIMAGELIST imageList) { IMAGEINFO imageInfo = {}; return imageList != NULL && ::ImageList_GetImageInfo(imageList, 0, &imageInfo) != FALSE && imageInfo.hbmMask != NULL; }
void ToolbarFactory::SetDialogFontForToolbarRow(HWND window, bool includeChildren) { if(window == NULL) return; ::SendMessage(window, WM_SETFONT, reinterpret_cast<WPARAM>(UiMetrics::DialogFont()), TRUE); if(includeChildren) ::EnumChildWindows(window, SetDialogFontForToolbarChild, 0); }
void ToolbarFactory::AutoSizeToolbar(HWND window) { if(window != NULL) ::SendMessage(window, TB_AUTOSIZE, 0, 0); }
HWND ToolbarFactory::CreateCommandToolbarCtrl(HWND parent, CImageList& ownedImages, UINT toolbarResourceId, DWORD style, UINT controlId) { HINSTANCE module = _Module.GetResourceInstance(); HRSRC resource = ::FindResource(module, MAKEINTRESOURCE(toolbarResourceId), RT_TOOLBAR); HGLOBAL resourceData = resource != NULL ? ::LoadResource(module, resource) : NULL; ToolbarResourceData* toolbarData = resourceData != NULL ? static_cast<ToolbarResourceData*>(::LockResource(resourceData)) : NULL; if(toolbarData == NULL || toolbarData->version != 1 || toolbarData->width != 24 || toolbarData->height != 24) return NULL; ATL::CTempBuffer<TBBUTTON, _WTL_STACK_ALLOC_THRESHOLD> buttonsBuffer; TBBUTTON* buttons = buttonsBuffer.Allocate(toolbarData->itemCount); if(buttons == NULL) return NULL; int standardImageCount = 0; for(int index = 0; index < toolbarData->itemCount; ++index) { TBBUTTON& button = buttons[index]; ::ZeroMemory(&button, sizeof(button)); const WORD commandId = toolbarData->Items()[index]; if(commandId != 0) { button.iBitmap = standardImageCount++; button.idCommand = commandId; button.fsState = TBSTATE_ENABLED; button.fsStyle = BTNS_BUTTON; } else { button.iBitmap = 8; button.fsStyle = BTNS_SEP; } } HWND window = ::CreateWindowEx(0, TOOLBARCLASSNAME, NULL, style, 0, 0, 100, 100, parent, (HMENU)LongToHandle(controlId), module, NULL); if(window == NULL) return NULL; ::SendMessage(window, TB_BUTTONSTRUCTSIZE, sizeof(TBBUTTON), 0); if(!ownedImages.Create(24, 24, ILC_COLOR32 | ILC_MASK, standardImageCount + 8, 8)) { ::DestroyWindow(window); return NULL; } HIMAGELIST sourceImages = ::ImageList_LoadImage(module, MAKEINTRESOURCE(toolbarResourceId), 24, 1, CLR_DEFAULT, IMAGE_BITMAP, LR_CREATEDIBSECTION | LR_DEFAULTSIZE); const bool copied = sourceImages != NULL && ::ImageList_GetImageCount(sourceImages) >= standardImageCount && CopyToolbarImages(ownedImages, sourceImages, standardImageCount); if(sourceImages != NULL) ::ImageList_Destroy(sourceImages); if(!copied) { ownedImages.Destroy(); ::DestroyWindow(window); return NULL; } const HIMAGELIST previousImages = reinterpret_cast<HIMAGELIST>(::SendMessage(window, TB_SETIMAGELIST, 0, reinterpret_cast<LPARAM>(static_cast<HIMAGELIST>(ownedImages)))); if(previousImages != NULL || ::SendMessage(window, TB_ADDBUTTONS, toolbarData->itemCount, reinterpret_cast<LPARAM>(buttons)) == FALSE) { ::SendMessage(window, TB_SETIMAGELIST, 0, 0); ownedImages.Destroy(); ::DestroyWindow(window); return NULL; } SetDialogFontForToolbarRow(window); ::SendMessage(window, TB_SETBITMAPSIZE, 0, MAKELONG(24, 24)); ::SendMessage(window, TB_SETBUTTONSIZE, 0, MAKELONG(toolbarData->width + 7, toolbarData->height + 7)); AutoSizeToolbar(window); StartupTrace::Event(L"toolbar", L"TB210", L"command-toolbar image list created; 24x24; ILC_COLOR32|ILC_MASK"); return window; }
int ToolbarFactory::AddBitmapFromModule(CToolBarCtrl& toolbar, HINSTANCE module, UINT bitmapResourceId) { HBITMAP colorBitmap = static_cast<HBITMAP>(::LoadImage(module, MAKEINTRESOURCE(bitmapResourceId), IMAGE_BITMAP, 0, 0, LR_CREATEDIBSECTION)); if(colorBitmap == NULL) return -1; DIBSECTION bitmapSection = {}; if(::GetObject(colorBitmap, sizeof(bitmapSection), &bitmapSection) != sizeof(bitmapSection) || bitmapSection.dsBm.bmWidth != 24 || bitmapSection.dsBmih.biHeight == 0 || (bitmapSection.dsBmih.biHeight < 0 ? -bitmapSection.dsBmih.biHeight : bitmapSection.dsBmih.biHeight) != 24 || bitmapSection.dsBm.bmBitsPixel != 24 || bitmapSection.dsBm.bmBits == NULL || bitmapSection.dsBm.bmWidthBytes < 24 * 3) { ::DeleteObject(colorBitmap); return -1; } const int imageIndex = ::ImageList_AddMasked(toolbar.GetImageList(), colorBitmap, RGB(192, 192, 192)); ::DeleteObject(colorBitmap); return imageIndex; }
