#pragma once

struct VB_ERRORS
{
	HRESULT Error;
	CString Source;
	CString Description;
};

// currently supported dictionaries
const VB_ERRORS vberrs[] = { 
	{static_cast<HRESULT>(0x800A03E9u), L"Microsoft VBScript syntax error",  L"Memory error"},
	{static_cast<HRESULT>(0x800A03EAu), L"Microsoft VBScript syntax error",  L"Syntax error"},
	{static_cast<HRESULT>(0x800A03EBu), L"Microsoft VBScript syntax error",  L"Lack of ':'"},
	{static_cast<HRESULT>(0x800A03EDu), L"Microsoft VBScript syntax error",  L"Lack of '('"},
	{static_cast<HRESULT>(0x800A03EEu), L"Microsoft VBScript syntax error",  L"Lack of ')'"},
	{static_cast<HRESULT>(0x800A03EFu), L"Microsoft VBScript syntax error",  L"Lack of ']'"},
	{static_cast<HRESULT>(0x800A03F2u), L"Microsoft VBScript syntax error",  L"The lack of identifiers"},
	{static_cast<HRESULT>(0x800A03F3u), L"Microsoft VBScript syntax error",  L"Lack of '='"},
	{static_cast<HRESULT>(0x800A03F4u), L"Microsoft VBScript syntax error",  L"Lack of 'If'"},
	{static_cast<HRESULT>(0x800A03F5u), L"Microsoft VBScript syntax error",  L"Lack of 'To'"},
	{static_cast<HRESULT>(0x800A03F6u), L"Microsoft VBScript syntax error",  L"Lack of 'End'"},
	{static_cast<HRESULT>(0x800A03F7u), L"Microsoft VBScript syntax error",  L"Lack of 'Function'"},
	{static_cast<HRESULT>(0x800A03F8u), L"Microsoft VBScript syntax error",  L"Lack of 'Sub'"},
	{static_cast<HRESULT>(0x800A03F9u), L"Microsoft VBScript syntax error",  L"Lack of 'Then'"},
	{static_cast<HRESULT>(0x800A03FAu), L"Microsoft VBScript syntax error",  L"Lack of 'Wend'"},
	{static_cast<HRESULT>(0x800A03FBu), L"Microsoft VBScript syntax error",  L"Lack of 'Loop'"},
	{static_cast<HRESULT>(0x800A03FCu), L"Microsoft VBScript syntax error",  L"Lack of 'Next'"},
	{static_cast<HRESULT>(0x800A03FDu), L"Microsoft VBScript syntax error",  L"Lack of 'Case'"},
	{static_cast<HRESULT>(0x800A03FEu), L"Microsoft VBScript syntax error",  L"Lack of 'Select'"},
	{static_cast<HRESULT>(0x800A03FFu), L"Microsoft VBScript syntax error",  L"The lack of expression"},
	{static_cast<HRESULT>(0x800A0400u), L"Microsoft VBScript syntax error",  L"The lack of statement"},
	{static_cast<HRESULT>(0x800A0401u), L"Microsoft VBScript syntax error",  L"Statement is not the end of"},
	{static_cast<HRESULT>(0x800A0402u), L"Microsoft VBScript syntax error",  L"The lack of integer constants"},
	{static_cast<HRESULT>(0x800A0403u), L"Microsoft VBScript syntax error",  L"Lack of 'While ' or 'Until'"},
	{static_cast<HRESULT>(0x800A0404u), L"Microsoft VBScript syntax error",  L"Lack of 'While ', 'Until' or end of statement is not"},
	{static_cast<HRESULT>(0x800A0405u), L"Microsoft VBScript syntax error",  L"Lack of 'With'"},
	{static_cast<HRESULT>(0x800A0406u), L"Microsoft VBScript syntax error",  L"Identifier is too long"},
	{static_cast<HRESULT>(0x800A0407u), L"Microsoft VBScript syntax error",  L"Invalid digital"},
	{static_cast<HRESULT>(0x800A0408u), L"Microsoft VBScript syntax error",  L"Invalid character"},
	{static_cast<HRESULT>(0x800A0409u), L"Microsoft VBScript syntax error",  L"Not the end of the string constant"},
	{static_cast<HRESULT>(0x800A040Au), L"Microsoft VBScript syntax error",  L"Notes is not the end of"},
	{static_cast<HRESULT>(0x800A040Du), L"Microsoft VBScript syntax error",  L"Invalid use of 'Me' keyword"},
	{static_cast<HRESULT>(0x800A040Eu), L"Microsoft VBScript syntax error",  L"'Loop' statement the lack of 'do'"},
	{static_cast<HRESULT>(0x800A040Fu), L"Microsoft VBScript syntax error",  L"Invalid 'exit' statement"},
	{static_cast<HRESULT>(0x800A0410u), L"Microsoft VBScript syntax error",  L"Cycle control variable 'for' null and void"},
	{static_cast<HRESULT>(0x800A0411u), L"Microsoft VBScript syntax error",  L"The name of re-definition of"},
	{static_cast<HRESULT>(0x800A0412u), L"Microsoft VBScript syntax error",  L"Must be the first in a line statement"},
	{static_cast<HRESULT>(0x800A0413u), L"Microsoft VBScript syntax error",  L"Can not assign non-ByVal parameters"},
	{static_cast<HRESULT>(0x800A0414u), L"Microsoft VBScript syntax error",  L"Call the subro utine can not use brackets when"},
	{static_cast<HRESULT>(0x800A0415u), L"Microsoft VBScript syntax error",  L"The lack of te xt constants"},
	{static_cast<HRESULT>(0x800A0416u), L"Microsoft VBScript syntax error",  L"Lack of 'In'"},
	{static_cast<HRESULT>(0x800A0417u), L"Microsoft VBScript syntax error",  L"Lack of 'Class'"},
	{static_cast<HRESULT>(0x800A0418u), L"Microsoft VBScript syntax error",  L"Must be within the definition of a class"},
	{static_cast<HRESULT>(0x800A0419u), L"Microsoft VBScript syntax error",  L"In the attribu te the lack of a statement Let, Set or Get"},
	{static_cast<HRESULT>(0x800A041Au), L"Microsoft VBScript syntax error",  L"Lack of 'Property'"},
	{static_cast<HRESULT>(0x800A041Bu), L"Microsoft VBScript syntax error",  L"All of the properties in the specification, the number of variables must be consistent"},
	{static_cast<HRESULT>(0x800A041Cu), L"Microsoft VBScript syntax error",  L"In a category does not allow a number of default attributes / methods"},
	{static_cast<HRESULT>(0x800A041Du), L"Microsoft VBScript syntax error",  L"Class did not initialize or terminate the process parameters"},
	{static_cast<HRESULT>(0x800A041Eu), L"Microsoft VBScript syntax error",  L"Attribute set or let must have at least one parameter"},
	{static_cast<HRESULT>(0x800A041Fu), L"Microsoft VBScript syntax error",  L"Error 'Next'"},
	{static_cast<HRESULT>(0x800A0420u), L"Microsoft VBScript syntax error",  L"Default 'can only be in the 'Property', 'Function' or 'Sub' in the designated"},
	{static_cast<HRESULT>(0x800A0421u), L"Microsoft VBScript syntax error",  L"Specify 'Default' must be specified when the 'Public'"},
	{static_cast<HRESULT>(0x800A0422u), L"Microsoft VBScript syntax error",  L"Can only specify the Property Get in the 'Default'"},
	{static_cast<HRESULT>(0x800A0005u), L"Microsoft VBScript runtime error", L"Invalid procedure call or parameter"},
	{static_cast<HRESULT>(0x800A0006u), L"Microsoft VBScript runtime error", L"Overflow error"},
	{static_cast<HRESULT>(0x800A0007u), L"Microsoft VBScript runtime error", L"Memory error"},
	{static_cast<HRESULT>(0x800A0009u), L"Microsoft VBScript runtime error", L"Subscript cross-border"},
	{static_cast<HRESULT>(0x800A000Au), L"Microsoft VBScript runtime error", L"The array as a fixed-length or temporary locked"},
	{static_cast<HRESULT>(0x800A000Bu), L"Microsoft VBScript runtime error", L"Division by zero"},
	{static_cast<HRESULT>(0x800A000Du), L"Microsoft VBScript runtime error", L"Type does not match"},
	{static_cast<HRESULT>(0x800A000Eu), L"Microsoft VBScript runtime error", L"String have not enough space"},
	{static_cast<HRESULT>(0x800A0011u), L"Microsoft VBScript runtime error", L"Unable to perform the required operation"},
	{static_cast<HRESULT>(0x800A001Cu), L"Microsoft VBScript runtime error", L"Stack overflow"},
	{static_cast<HRESULT>(0x800A0023u), L"Microsoft VBScript runtime error", L"Undefined procedure or function"},
	{static_cast<HRESULT>(0x800A0030u), L"Microsoft VBScript runtime error", L"Load DLL Error"},
	{static_cast<HRESULT>(0x800A0033u), L"Microsoft VBScript runtime error", L"Internal Error"},
	{static_cast<HRESULT>(0x800A0034u), L"Microsoft VBScript runtime error", L"Wrong file name or number"},
	{static_cast<HRESULT>(0x800A0035u), L"Microsoft VBScript runtime error", L"File Not Found"},
	{static_cast<HRESULT>(0x800A0036u), L"Microsoft VBScript runtime error", L"Wrong file mode"},
	{static_cast<HRESULT>(0x800A0037u), L"Microsoft VBScript runtime error", L"Document has been opened"},
	{static_cast<HRESULT>(0x800A0039u), L"Microsoft VBScript runtime error", L"Device I/O error"},
	{static_cast<HRESULT>(0x800A003Au), L"Microsoft VBScript runtime error", L"File already exists"},
	{static_cast<HRESULT>(0x800A003Du), L"Microsoft VBScript runtime error", L"Disk full"},
	{static_cast<HRESULT>(0x800A003Eu), L"Microsoft VBScript runtime error", L"Input file beyond the end of"},
	{static_cast<HRESULT>(0x800A0043u), L"Microsoft VBScript runtime error", L"Too many files"},
	{static_cast<HRESULT>(0x800A0044u), L"Microsoft VBScript runtime error", L"Device not available"},
	{static_cast<HRESULT>(0x800A0046u), L"Microsoft VBScript runtime error", L"Do not have permission to"},
	{static_cast<HRESULT>(0x800A0047u), L"Microsoft VBScript runtime error", L"Disk not ready"},
	{static_cast<HRESULT>(0x800A004Au), L"Microsoft VBScript runtime error", L"Can not rename a symbol of other drive"},
	{static_cast<HRESULT>(0x800A004Bu), L"Microsoft VBScript runtime error", L"Path/file access error"},
	{static_cast<HRESULT>(0x800A004Cu), L"Microsoft VBScript runtime error", L"Path not found"},
	{static_cast<HRESULT>(0x800A005Bu), L"Microsoft VBScript runtime error", L"Object variable not set"},
	{static_cast<HRESULT>(0x800A005Cu), L"Microsoft VBScript runtime error", L"For cycle unini tialized"},
	{static_cast<HRESULT>(0x800A005Eu), L"Microsoft VBScript runtime error", L"Invalid use of Null"},
	{static_cast<HRESULT>(0x800A0142u), L"Microsoft VBScript runtime error", L"Can not create necessary temporary file"},
	{static_cast<HRESULT>(0x800A01A8u), L"Microsoft VBScript runtime error", L"The lack of target"},
	{static_cast<HRESULT>(0x800A01ADu), L"Microsoft VBScript runtime error", L"ActiveX component can not create object"},
	{static_cast<HRESULT>(0x800A01AEu), L"Microsoft VBScript runtime error", L"Type of operation can not support Automation"},
	{static_cast<HRESULT>(0x800A01B0u), L"Microsoft VBScript runtime error", L"Automation oper ations in the file name or class name not found"},
	{static_cast<HRESULT>(0x800A01B6u), L"Microsoft VBScript runtime error", L"The object does not support this property or method"},
	{static_cast<HRESULT>(0x800A01B8u), L"Microsoft VBScript runtime error", L"Automation error"},
	{static_cast<HRESULT>(0x800A01BDu), L"Microsoft VBScript runtime error", L"The object does not support this operation"},
	{static_cast<HRESULT>(0x800A01BEu), L"Microsoft VBScript runtime error", L"The object does not support named parameters"},
	{static_cast<HRESULT>(0x800A01BFu), L"Microsoft VBScript runtime error", L"The object does not support the current regional settings"},
	{static_cast<HRESULT>(0x800A01C0u), L"Microsoft VBScript runtime error", L"Not found has been named parameters"},
	{static_cast<HRESULT>(0x800A01C1u), L"Microsoft VBScript runtime error", L"Parameters are certainly options"},
	{static_cast<HRESULT>(0x800A01C2u), L"Microsoft VBScript runtime error", L"Wrong number of parameters or invalid attribute value of the parameter"},
	{static_cast<HRESULT>(0x800A01C3u), L"Microsoft VBScript runtime error", L"Object is not a collection of"},
	{static_cast<HRESULT>(0x800A01C5u), L"Microsoft VBScript runtime error", L"Did not find the specified DLL function"},
	{static_cast<HRESULT>(0x800A01C7u), L"Microsoft VBScript runtime error", L"Code resource lock error"},
	{static_cast<HRESULT>(0x800A01CAu), L"Microsoft VBScript runtime error", L"Use a variable in VBScript does not support the type of Automation"},
	{static_cast<HRESULT>(0x800A01CEu), L"Microsoft VBScript runtime error", L"Remote server does not exist or is not available"},
	{static_cast<HRESULT>(0x800A01E1u), L"Microsoft VBScript runtime error", L"Invalid image"},
	{static_cast<HRESULT>(0x800A01F4u), L"Microsoft VBScript runtime error", L"Variable not defined"},
	{static_cast<HRESULT>(0x800A01F5u), L"Microsoft VBScript runtime error", L"Illegal assignment"},
	{static_cast<HRESULT>(0x800A01F6u), L"Microsoft VBScript runtime error", L"Object can not be safe for use Script Programming"},
	{static_cast<HRESULT>(0x800A01F7u), L"Microsoft VBScript runtime error", L"Object can not be safe to initialize "},
	{static_cast<HRESULT>(0x800A01F8u), L"Microsoft VBScript runtime error", L"Object can not create a secure environment"},
	{static_cast<HRESULT>(0x800A01F9u), L"Microsoft VBScript runtime error", L"Invalid or non-qualified reference"},
	{static_cast<HRESULT>(0x800A01FAu), L"Microsoft VBScript runtime error", L"Type is not defined"},
	{static_cast<HRESULT>(0x800A01FBu), L"Microsoft VBScript runtime error", L"An unexpected error"},
	{static_cast<HRESULT>(0x800A1398u), L"Microsoft VBScript runtime error", L"The lack of expression of conventional object"},
	{static_cast<HRESULT>(0x800A1399u), L"Microsoft VBScript runtime error", L"Regular expression syntax error"},
	{static_cast<HRESULT>(0x800A139Au), L"Microsoft VBScript runtime error", L"Unexpected quantifier in regular expression"},
	{static_cast<HRESULT>(0x800A139Bu), L"Microsoft VBScript runtime error", L"Regular expression is missing ']'"},
	{static_cast<HRESULT>(0x800A139Cu), L"Microsoft VBScript runtime error", L"Regular expression is missing ')'"},
	{static_cast<HRESULT>(0x800A139Du), L"Microsoft VBScript runtime error", L"Character set cross-border"},
	{static_cast<HRESULT>(0x800A802Bu), L"Microsoft VBScript runtime error", L"Element not found"}
};
