#include "stdafx.h"
#include "ScriptToolbarManagerDlg.h"
#include "RuntimeLocalization.h"
#include "utils.h"

LRESULT CScriptToolbarManagerDlg::OnInitDialog(UINT, WPARAM, LPARAM, BOOL&) { FbeApplyRuntimeDialogLocalization(m_hWnd, IDD); m_list = GetDlgItem(IDC_SCRIPT_PANELS_LIST); m_lastCommitted=m_manager.Collection().Items(); Refresh(); return TRUE; }
CString CScriptToolbarManagerDlg::SelectedId() const { const int index=m_list.GetCurSel(); const std::vector<ScriptToolbarDefinition>& items=m_manager.Collection().Items(); return index>=0 && index<static_cast<int>(items.size()) ? items[index].id : CString(); }
void CScriptToolbarManagerDlg::Refresh(const CString& preferredId) { CString selected=preferredId.IsEmpty()?SelectedId():preferredId; m_list.ResetContent(); const std::vector<ScriptToolbarDefinition>& items=m_manager.Collection().Items(); for(size_t i=0;i<items.size();++i) { int row=m_list.AddString(items[i].name); if(items[i].id==selected) m_list.SetCurSel(row); } if(m_list.GetCurSel()<0 && m_list.GetCount()) m_list.SetCurSel(0); BOOL handled=FALSE; OnSelection(0,0,NULL,handled); }
LRESULT CScriptToolbarManagerDlg::OnSelection(WORD, WORD, HWND, BOOL&) { m_renameEditing=false; const ScriptToolbarDefinition* item=m_manager.Collection().Find(SelectedId()); if(item) { SetDlgItemText(IDC_SCRIPT_PANEL_NAME,item->name); CheckDlgButton(IDC_SCRIPT_PANEL_VISIBLE,item->visible?BST_CHECKED:BST_UNCHECKED); GetDlgItem(IDC_SCRIPT_PANEL_DELETE).EnableWindow(item->id!=L"scripts-main"); } return 0; }
CString CScriptToolbarManagerDlg::NextDefaultPanelName() const { return m_manager.Collection().NextDefaultName(FbeLoadRuntimeStringByKey(L"fbe.script_toolbar_manager.default_name")); }
bool CScriptToolbarManagerDlg::Commit(const CString& preferredId) { if(!m_changed(m_lastCommitted, m_manager.Collection().Items())) { m_manager.Collection().Items()=m_lastCommitted; U::MessageBox(m_hWnd,FbeLoadRuntimeStringByKey(L"fbe.script_toolbar_manager.save_failed",L"Не удалось сохранить настройки панелей скриптов."),FbeLoadRuntimeStringByKey(L"fbe.script_toolbar_manager.caption",L"FictionBook Editor"),MB_OK|MB_ICONERROR); Refresh(); return false; } m_lastCommitted=m_manager.Collection().Items(); Refresh(preferredId); return true; }
LRESULT CScriptToolbarManagerDlg::OnCreatePanel(WORD, WORD, HWND, BOOL&) { const ScriptToolbarDefinition& created=m_manager.Create(NextDefaultPanelName()); const CString createdId=created.id; if(Commit(createdId)) { const HWND name=GetDlgItem(IDC_SCRIPT_PANEL_NAME); ::SetFocus(name); ::SendMessage(name,EM_SETSEL,0,-1); } return 0; }
bool CScriptToolbarManagerDlg::ApplyRename() { CString name; GetDlgItemText(IDC_SCRIPT_PANEL_NAME,name); name.Trim(); const CString selected=SelectedId(); if(name.IsEmpty() || selected.IsEmpty()) return false; const std::vector<ScriptToolbarDefinition>& items=m_manager.Collection().Items(); for(size_t i=0;i<items.size();++i) if(items[i].id!=selected && items[i].name.CompareNoCase(name)==0) return false; if(!m_manager.Rename(selected,name)) return false; m_renameEditing=false; return Commit(selected); }
LRESULT CScriptToolbarManagerDlg::OnRename(WORD, WORD, HWND, BOOL&) { if(m_renameEditing) { ApplyRename(); return 0; } const HWND name=GetDlgItem(IDC_SCRIPT_PANEL_NAME); ::SetFocus(name); ::SendMessage(name,EM_SETSEL,0,-1); m_renameEditing=true; return 0; }
LRESULT CScriptToolbarManagerDlg::OnDelete(WORD, WORD, HWND, BOOL&) { const int current=m_list.GetCurSel(); const CString previous=current>0 ? CString(m_manager.Collection().Items()[current-1].id) : CString(); if(m_manager.Delete(SelectedId())) Commit(previous); return 0; }
LRESULT CScriptToolbarManagerDlg::OnUp(WORD, WORD, HWND, BOOL&) { int i=m_list.GetCurSel(); if(i>0 && m_manager.Move(SelectedId(),static_cast<size_t>(i-1))) Commit(); return 0; }
LRESULT CScriptToolbarManagerDlg::OnDown(WORD, WORD, HWND, BOOL&) { int i=m_list.GetCurSel(); if(i>=0 && i+1<m_list.GetCount() && m_manager.Move(SelectedId(),static_cast<size_t>(i+1))) Commit(); return 0; }
LRESULT CScriptToolbarManagerDlg::OnVisible(WORD, WORD, HWND, BOOL&) { m_manager.SetVisible(SelectedId(),IsDlgButtonChecked(IDC_SCRIPT_PANEL_VISIBLE)==BST_CHECKED); Commit(); return 0; }
LRESULT CScriptToolbarManagerDlg::OnClose(WORD, WORD, HWND, BOOL&) { EndDialog(IDCANCEL); return 0; }
BOOL CScriptToolbarManagerDlg::PreTranslateMessage(MSG* message) { const HWND name=GetDlgItem(IDC_SCRIPT_PANEL_NAME); if(message->hwnd==name && message->message==WM_KEYDOWN) { if(message->wParam==VK_RETURN && m_renameEditing) { ApplyRename(); return TRUE; } if(message->wParam==VK_ESCAPE && m_renameEditing) { m_renameEditing=false; BOOL handled=FALSE; OnSelection(0,0,NULL,handled); return TRUE; } } return FALSE; }
