<#
.SYNOPSIS
Генерирует Win32 DIALOGEX-ресурсы малых диалогов FBE из JSON-каталога локализации.

.DESCRIPTION
Скрипт читает `localization/app-ui/fbe-small-dialogs.json` и создаёт
`FBESmallDialogs.generated.rc2` для русской и украинской resource DLL.
В generated-файл входят `IDD_TABLE`, `IDD_INPUTBOX`, `IDD_ADDIMAGE`,
`IDD_TOOLS_SETTINGS`, `IDD_ABOUTBOX`, `IDD_CUSTOMSAVEDLG` и
`IDD_SETTINGS_WORDS`, `IDD_HOTKEYS`, `IDD_FIND` и `IDD_REPLACE`.
#>
[CmdletBinding()]
param(
    [string[]]$Languages = @("ru-RU", "uk-UA")
)

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$catalogPath = Join-Path $repoRoot "localization\app-ui\fbe-small-dialogs.json"
$catalog = Get-Content -Raw -LiteralPath $catalogPath | ConvertFrom-Json -Depth 40
$outputByLanguage = @{
    "ru-RU" = Join-Path $repoRoot "src\locales\res_rus\FBESmallDialogs.generated.rc2"
    "uk-UA" = Join-Path $repoRoot "src\locales\res_ukr\FBESmallDialogs.generated.rc2"
}
function ConvertTo-RcStringLiteral { param([AllowNull()][string]$Text) if ($null -eq $Text) { return "" } return $Text.Replace('"','""') }
function Get-Text { param([string]$Key,[string]$Language)
    $fullKey="fbe.dialog.$Key"
    $entry=$catalog.strings.PSObject.Properties[$fullKey]
    if(-not $entry){ throw "В каталоге нет строки: $fullKey" }
    $tr=$entry.Value.translations.PSObject.Properties[$Language]
    if(-not $tr -or [string]::IsNullOrWhiteSpace([string]$tr.Value)){ throw "У $fullKey нет перевода для $Language" }
    return ConvertTo-RcStringLiteral ([string]$tr.Value)
}
$utf16LeBom=[Text.UnicodeEncoding]::new($false,$true)
foreach($language in $Languages){
    if(-not $outputByLanguage.ContainsKey($language)){ throw "Для языка $language не задан output." }
    $l=[Collections.Generic.List[string]]::new()
    $l.Add("// Автоматически сгенерировано из localization/app-ui/fbe-small-dialogs.json.")
    $l.Add("// Не редактируйте вручную: используйте tools/localization/update-fbe-small-dialog-resources.ps1.")
    $l.Add("")
    $l.Add("IDD_TABLE DIALOGEX 0, 0, 260, 46")
    $l.Add("STYLE DS_SETFONT | DS_MODALFRAME | DS_FIXEDSYS | DS_CENTER | WS_POPUP | WS_CAPTION | WS_SYSMENU")
    $l.Add('CAPTION "' + (Get-Text 'idd_table.caption' $language) + '"')
    $l.Add('FONT 8, "MS Shell Dlg", 400, 0, 0x1')
    $l.Add("BEGIN")
    $l.Add('    DEFPUSHBUTTON   "' + (Get-Text 'idd_table.ok' $language) + '",IDOK,203,7,50,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_table.cancel' $language) + '",IDCANCEL,203,24,50,14')
    $l.Add('    LTEXT           "' + (Get-Text 'idd_table.rows_label' $language) + '",IDC_STATIC,7,22,150,8')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_table.header_row' $language) + '",IDC_CHECK_TABLE_TITLE,')
    $l.Add('                    "Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,7,187,10')
    $l.Add('    EDITTEXT        IDC_EDIT_TABLE_ROWS,157,19,35,14,ES_AUTOHSCROLL | ES_NUMBER')
    $l.Add('    CONTROL         "",IDC_SPIN_TABLE_ROWS,"msctls_updown32",UDS_WRAP | UDS_SETBUDDYINT | UDS_ALIGNRIGHT | UDS_AUTOBUDDY | UDS_ARROWKEYS | UDS_NOTHOUSANDS,192,19,11,14')
    $l.Add("END")
    $l.Add("")
    $l.Add("IDD_INPUTBOX DIALOGEX 0, 0, 290, 70")
    $l.Add("STYLE DS_SETFONT | DS_MODALFRAME | DS_CENTER | WS_POPUP | WS_CAPTION | WS_SYSMENU")
    $l.Add('CAPTION "' + (Get-Text 'idd_inputbox.caption' $language) + '"')
    $l.Add('FONT 9, "Tahoma", 0, 0, 0x0')
    $l.Add("BEGIN")
    $l.Add('    LTEXT           "' + (Get-Text 'idd_inputbox.prompt' $language) + '",IDC_PROMPT,7,7,273,18')
    $l.Add('    EDITTEXT        IDC_INPUT,7,31,273,12,ES_AUTOHSCROLL')
    $l.Add('    DEFPUSHBUTTON   "' + (Get-Text 'idd_inputbox.yes' $language) + '",IDYES,155,49,39,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_inputbox.no' $language) + '",IDNO,198,49,39,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_inputbox.cancel' $language) + '",IDCANCEL,241,49,39,14')
    $l.Add("END")
    $l.Add("")
    $l.Add("IDD_ADDIMAGE DIALOGEX 0, 0, 147, 66")
    $l.Add("STYLE DS_SETFONT | DS_MODALFRAME | DS_FIXEDSYS | WS_POPUP | WS_CAPTION")
    $l.Add('CAPTION "' + (Get-Text 'idd_addimage.caption' $language) + '"')
    $l.Add('FONT 8, "MS Shell Dlg", 400, 0, 0x1')
    $l.Add("BEGIN")
    $l.Add('    DEFPUSHBUTTON   "' + (Get-Text 'idd_addimage.yes' $language) + '",IDYES,21,31,49,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_addimage.no' $language) + '",IDCANCEL,77,31,49,14')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_addimage.ask_again' $language) + '",IDC_ADDIMAGE_ASKAGAIN,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,28,53,91,10')
    $l.Add('    LTEXT           "' + (Get-Text 'idd_addimage.text' $language) + '",IDS_ADD_CLEARIMG_TEXT,29,11,110,10')
    $l.Add('    ICON            IDR_MAINFRAME,IDC_ADDIMAGE_ICON,3,6,20,20')
    $l.Add("END")
    $l.Add("")
    $l.Add("IDD_TOOLS_SETTINGS DIALOGEX 0, 0, 266, 282")
    $l.Add("STYLE DS_SETFONT | DS_MODALFRAME | DS_CENTER | WS_POPUP | WS_VISIBLE | WS_CAPTION | WS_SYSMENU")
    $l.Add("EXSTYLE WS_EX_APPWINDOW")
    $l.Add('CAPTION "' + (Get-Text 'idd_tools_settings.caption' $language) + '"')
    $l.Add('FONT 8, "Microsoft Sans Serif", 400, 0, 0xCC')
    $l.Add("BEGIN")
    $l.Add('    CONTROL         "",IDC_TAB_CTRL,"SysTabControl32",0x0,0,0,266,257')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_tools_settings.ok' $language) + '",IDOK,142,259,55,15')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_tools_settings.cancel' $language) + '",IDCANCEL,205,259,55,15')
    $l.Add("END")
    $l.Add("")
    $l.Add("IDD_ABOUTBOX DIALOGEX 0, 0, 300, 151")
    $l.Add("STYLE DS_SETFONT | DS_CENTER | WS_POPUP | WS_VISIBLE | WS_CAPTION | WS_SYSMENU | WS_THICKFRAME")
    $l.Add('CAPTION "' + (Get-Text 'idd_aboutbox.caption' $language) + '"')
    $l.Add('FONT 9, "Tahoma", 0, 0, 0x0')
    $l.Add("BEGIN")
    $l.Add('    DEFPUSHBUTTON   "' + (Get-Text 'idd_aboutbox.ok' $language) + '",IDOK,249,133,44,14')
    $l.Add('    CONTROL         248,IDC_AB_STATIC_BANNER,"Static",SS_BITMAP | SS_NOTIFY | NOT WS_VISIBLE,6,6,56,123,WS_EX_CLIENTEDGE')
    $l.Add('    CONTROL         "",IDC_AB_BANNER,"Static",SS_OWNERDRAW | SS_NOTIFY | NOT WS_VISIBLE,6,6,57,123,WS_EX_CLIENTEDGE')
    $l.Add('    ICON            IDR_MAINFRAME,IDC_STATIC_AB_APPICON,73,8,20,20')
    $l.Add('    EDITTEXT        IDC_STATIC_AB_APPNAMEVER,99,8,191,12,ES_READONLY | NOT WS_BORDER | NOT WS_TABSTOP')
    $l.Add('    LTEXT           "' + (Get-Text 'idd_aboutbox.build' $language) + '",IDC_STATIC_BUILD,101,20,40,8')
    $l.Add('    EDITTEXT        IDC_BUILDSTAMP,142,20,148,12,ES_READONLY | NOT WS_BORDER | NOT WS_TABSTOP')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_aboutbox.link' $language) + '",IDC_SYSLINK_AB_LINKS,')
    $l.Add('                    "SysLink",0x0,101,32,188,8')
    $l.Add('    EDITTEXT        IDC_CONTRIBS,70,51,223,77,ES_MULTILINE | ES_AUTOVSCROLL | ES_READONLY | ES_WANTRETURN | NOT WS_BORDER | WS_VSCROLL | NOT WS_TABSTOP,WS_EX_STATICEDGE')
    $l.Add('    CONTROL         "Static",IDC_TEXT_STATUS,"Static",SS_LEFTNOWORDWRAP | WS_GROUP,24,137,180,8')
    $l.Add('    CONTROL         400,IDC_PIC_UPDATE,"Static",SS_BITMAP,9,136,9,9')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_aboutbox.update' $language) + '",IDC_UPDATE,195,133,49,14,NOT WS_VISIBLE')
    $l.Add("END")
    $l.Add("")
    $l.Add("IDD_CUSTOMSAVEDLG DIALOGEX 0, 0, 415, 18")
    $l.Add("STYLE DS_SETFONT | DS_3DLOOK | DS_CONTROL | WS_CHILD | WS_CLIPSIBLINGS | WS_CLIPCHILDREN")
    $l.Add('FONT 8, "Tahoma", 0, 0, 0x0')
    $l.Add("BEGIN")
    $l.Add('    LTEXT           "' + (Get-Text 'idd_customsavedlg.encoding' $language) + '",IDC_STATIC,68,2,41,10')
    $l.Add('    COMBOBOX        IDC_ENCODING,130,0,164,104,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP')
    $l.Add("END")
    $l.Add("")
    $l.Add("IDD_SETTINGS_WORDS DIALOGEX 0, 0, 266, 227")
    $l.Add("STYLE DS_SETFONT | DS_FIXEDSYS | WS_CHILD")
    $l.Add('FONT 8, "MS Shell Dlg", 400, 0, 0x1')
    $l.Add("BEGIN")
    $l.Add('    EDITTEXT        IDC_EDIT_NEW,16,169,165,14,ES_AUTOHSCROLL')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_settings_words.add' $language) + '",IDC_BUTTON_ADD,192,169,50,14')
    $l.Add('    GROUPBOX        "' + (Get-Text 'idd_settings_words.group' $language) + '",IDC_STATIC_WORDS_CHEVRON,7,8,252,183')
    $l.Add('    CONTROL         "",IDC_LIST_WORDS,"SysListView32",LVS_REPORT | LVS_SHOWSELALWAYS | LVS_SORTDESCENDING | LVS_OWNERDATA | WS_BORDER | WS_TABSTOP,15,25,230,115,WS_EX_CLIENTEDGE')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_settings_words.show_exclusions' $language) + '",IDC_CHECK_SHOW_EXCLUSIONS,')
    $l.Add('                    "Button",BS_AUTOCHECKBOX | WS_TABSTOP,15,201,235,10')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_settings_words.select_all' $language) + '",IDC_CHECK_SELALL,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,17,151,95,10')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_settings_words.remove_selected' $language) + '",IDC_BUTTON_REMOVESEL,104,148,78,14')
    $l.Add('    EDITTEXT        IDC_EDIT_LV,202,7,43,14,ES_AUTOHSCROLL | NOT WS_VISIBLE | NOT WS_TABSTOP,WS_EX_CLIENTEDGE | WS_EX_STATICEDGE')
    $l.Add("END")
    $l.Add("")
    $l.Add("IDD_HOTKEYS DIALOGEX 0, 0, 249, 227")
    $l.Add("STYLE DS_SETFONT | WS_CHILD | WS_SYSMENU")
    $l.Add('FONT 9, "Tahoma", 400, 0, 0xCC')
    $l.Add("BEGIN")
    $l.Add('    LISTBOX         IDC_LIST_HOTKEYS_GROUPS,7,21,70,88,LBS_NOINTEGRALHEIGHT | NOT WS_BORDER | WS_VSCROLL | WS_TABSTOP,WS_EX_STATICEDGE')
    $l.Add('    LISTBOX         IDC_LIST_HOTKEYS,83,21,132,88,LBS_NOINTEGRALHEIGHT | NOT WS_BORDER | WS_VSCROLL | WS_HSCROLL | WS_TABSTOP,WS_EX_STATICEDGE')
    $l.Add('    GROUPBOX        "' + (Get-Text 'idd_hotkeys.description' $language) + '",IDC_STATIC_HOTKEY_DESCRIPTION,7,180,208,33,WS_TABSTOP')
    $l.Add('    EDITTEXT        IDC_EDIT_HOTKEY,41,121,94,14,ES_MULTILINE | ES_AUTOHSCROLL')
    $l.Add('    LTEXT           "' + (Get-Text 'idd_hotkeys.groups' $language) + '",IDC_STATIC_HOTKEYS_GROUPS,9,11,68,8,WS_TABSTOP')
    $l.Add('    LTEXT           "' + (Get-Text 'idd_hotkeys.commands' $language) + '",IDC_STATIC_HOTKEYS,85,11,120,8,WS_TABSTOP')
    $l.Add('    LTEXT           "' + (Get-Text 'idd_hotkeys.shortcut' $language) + '",IDC_STATIC,10,124,31,8,WS_TABSTOP')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_hotkeys.default' $language) + '",IDC_BUTTON_DEFAULT,151,125,55,14')
    $l.Add('    EDITTEXT        IDC_EDIT_HOTKEY_DESCRIPTION,9,189,202,22,ES_MULTILINE | ES_AUTOVSCROLL | ES_READONLY | NOT WS_BORDER | WS_VSCROLL')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_hotkeys.delete' $language) + '",IDC_BUTTON_HOTKEY_DELETE,151,143,54,14')
    $l.Add('    GROUPBOX        "' + (Get-Text 'idd_hotkeys.actions' $language) + '",IDC_STATIC,143,114,72,65')
    $l.Add('    GROUPBOX        "' + (Get-Text 'idd_hotkeys.collision' $language) + '",IDC_STATIC_HOTKEY_COLLISION,7,138,129,41')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_hotkeys.assign' $language) + '",IDC_BUTTON_HOTKEY_ASSIGN,151,161,54,14,WS_DISABLED')
    $l.Add('    EDITTEXT        IDC_EDIT_HOTKEY_COLLISION,14,150,115,24,ES_MULTILINE | ES_AUTOVSCROLL | ES_READONLY | NOT WS_BORDER | WS_VSCROLL')
    $l.Add("END")
    $l.Add("")
    $l.Add("IDD_FIND DIALOGEX 0, 0, 295, 76")
    $l.Add("STYLE DS_SETFONT | DS_MODALFRAME | DS_CENTER | WS_POPUP | WS_VISIBLE | WS_CAPTION | WS_SYSMENU")
    $l.Add('CAPTION "' + (Get-Text 'idd_find.caption' $language) + '"')
    $l.Add('FONT 9, "Tahoma", 0, 0, 0x0')
    $l.Add("BEGIN")
    $l.Add('    LTEXT           "' + (Get-Text 'idd_find.find_what' $language) + '",IDC_FIND_LABEL_TEXT,7,9,40,8')
    $l.Add('    COMBOBOX        IDC_TEXT,49,7,183,62,CBS_DROPDOWN | CBS_AUTOHSCROLL | WS_VSCROLL | WS_GROUP | WS_TABSTOP')
    $l.Add('    DEFPUSHBUTTON   "' + (Get-Text 'idd_find.find_next' $language) + '",ID_FIND_NEXT,238,7,50,14,WS_GROUP')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_find.whole_word' $language) + '",IDC_WHOLE,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,30,125,13')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_find.match_case' $language) + '",IDC_MATCHCASE,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,43,125,13')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_find.regexp' $language) + '",IDC_REGEXP,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,56,125,13')
    $l.Add('    GROUPBOX        "' + (Get-Text 'idd_find.direction' $language) + '",IDC_FIND_DIRECTION_GROUP,160,30,72,38,WS_GROUP')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_find.up' $language) + '",IDC_UP,"Button",BS_AUTORADIOBUTTON | WS_TABSTOP,167,41,58,11')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_find.down' $language) + '",IDC_DOWN,"Button",BS_AUTORADIOBUTTON,167,52,58,11')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_find.cancel' $language) + '",IDCANCEL,238,24,50,14')
    $l.Add("END")
    $l.Add("")
    $l.Add("IDD_REPLACE DIALOGEX 0, 0, 295, 87")
    $l.Add("STYLE DS_SETFONT | DS_MODALFRAME | DS_CENTER | WS_POPUP | WS_VISIBLE | WS_CAPTION | WS_SYSMENU")
    $l.Add('CAPTION "' + (Get-Text 'idd_replace.caption' $language) + '"')
    $l.Add('FONT 9, "Tahoma", 0, 0, 0x0')
    $l.Add("BEGIN")
    $l.Add('    LTEXT           "' + (Get-Text 'idd_replace.find_what' $language) + '",IDC_REPLACE_LABEL_TEXT,7,9,45,8,NOT WS_GROUP')
    $l.Add('    LTEXT           "' + (Get-Text 'idd_replace.replace_with' $language) + '",IDC_REPLACE_LABEL_REPLACE,7,25,45,8,NOT WS_GROUP')
    $l.Add('    COMBOBOX        IDC_TEXT,53,7,179,62,CBS_DROPDOWN | CBS_AUTOHSCROLL | WS_VSCROLL | WS_TABSTOP')
    $l.Add('    COMBOBOX        IDC_REPLACE,53,23,179,62,CBS_DROPDOWN | CBS_AUTOHSCROLL | WS_VSCROLL | WS_TABSTOP')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_replace.whole_word' $language) + '",IDC_WHOLE,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,41,125,13')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_replace.match_case' $language) + '",IDC_MATCHCASE,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,54,125,13')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_replace.regexp' $language) + '",IDC_REGEXP,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,7,67,125,13')
    $l.Add('    GROUPBOX        "' + (Get-Text 'idd_replace.direction' $language) + '",IDC_REPLACE_DIRECTION_GROUP,160,40,72,38,WS_GROUP')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_replace.up' $language) + '",IDC_UP,"Button",BS_AUTORADIOBUTTON | WS_TABSTOP,167,51,58,11')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_replace.down' $language) + '",IDC_DOWN,"Button",BS_AUTORADIOBUTTON,167,62,58,11')
    $l.Add('    DEFPUSHBUTTON   "' + (Get-Text 'idd_replace.find_next' $language) + '",ID_FIND_NEXT,238,7,50,14,WS_GROUP')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_replace.replace_one' $language) + '",IDC_REPLACE_ONE,238,25,50,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_replace.replace_all' $language) + '",IDC_REPLACE_ALL,238,43,50,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_replace.cancel' $language) + '",IDCANCEL,238,61,50,14')
    $l.Add("END")
    $l.Add("")
    $l.Add("IDD_SPELL_CHECK DIALOGEX 0, 0, 273, 135")
    $l.Add("STYLE DS_SETFONT | DS_MODALFRAME | DS_CENTER | WS_POPUP | WS_CAPTION | WS_SYSMENU")
    $l.Add('CAPTION "' + (Get-Text 'idd_spell_check.caption' $language) + '"')
    $l.Add('FONT 8, "Tahoma", 400, 0, 0x1')
    $l.Add("BEGIN")
    $l.Add('    DEFPUSHBUTTON   "' + (Get-Text 'idd_spell_check.cancel' $language) + '",IDCANCEL,216,112,50,14')
    $l.Add('    LTEXT           "' + (Get-Text 'idd_spell_check.not_in_dictionary' $language) + '",IDC_STATIC,7,14,64,8')
    $l.Add('    EDITTEXT        IDC_SPELL_BEDWORD,72,12,194,12,ES_AUTOHSCROLL')
    $l.Add('    LTEXT           "' + (Get-Text 'idd_spell_check.replace_with' $language) + '",IDC_STATIC,8,30,46,8')
    $l.Add('    EDITTEXT        IDC_SPELL_REPLACEMENT,72,29,194,12,ES_AUTOHSCROLL')
    $l.Add('    LTEXT           "' + (Get-Text 'idd_spell_check.suggestions' $language) + '",IDC_STATIC,7,47,46,8')
    $l.Add('    LISTBOX         IDC_SPELL_SUGG_LIST,7,58,145,68,LBS_SORT | LBS_NOINTEGRALHEIGHT | WS_VSCROLL | WS_TABSTOP')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_spell_check.ignore' $language) + '",IDC_SPELL_IGNORE,159,58,50,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_spell_check.ignore_all' $language) + '",IDC_SPELL_IGNOREALL,216,58,50,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_spell_check.change' $language) + '",IDC_SPELL_CHANGE,159,76,50,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_spell_check.change_all' $language) + '",IDC_SPELL_CHANGEALL,216,76,50,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_spell_check.add' $language) + '",IDC_SPELL_ADD,159,94,50,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_spell_check.suggest' $language) + '",IDC_SPELL_SUGGEST,216,94,50,14,WS_DISABLED')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_spell_check.undo' $language) + '",IDC_SPELL_UNDO,159,112,50,14,WS_DISABLED')
    $l.Add("END")
    $l.Add("")
    $l.Add("IDD_WORDS DIALOGEX 0, 0, 366, 323")
    $l.Add("STYLE DS_SETFONT | DS_CENTER | WS_POPUP | WS_CAPTION | WS_SYSMENU | WS_THICKFRAME")
    $l.Add('CAPTION "' + (Get-Text 'idd_words.caption' $language) + '"')
    $l.Add('FONT 9, "Tahoma", 0, 0, 0x1')
    $l.Add("BEGIN")
    $l.Add('    CONTROL         "' + (Get-Text 'idd_words.list' $language) + '",IDC_WLIST,"SysListView32",LVS_REPORT | LVS_OWNERDATA | WS_TABSTOP,7,7,354,208,WS_EX_CLIENTEDGE')
    $l.Add('    DEFPUSHBUTTON   "' + (Get-Text 'idd_words.ok' $language) + '",IDOK,301,233,40,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_words.cancel' $language) + '",IDCANCEL,301,253,40,14')
    $l.Add('    EDITTEXT        IDC_REDIT,7,270,41,12,NOT WS_VISIBLE | NOT WS_TABSTOP')
    $l.Add('    CONTROL         "' + (Get-Text 'idd_words.show_hide_exclusions' $language) + '",IDC_CHECK_SHOWHIDE_EXCLS,')
    $l.Add('                    "Button",BS_AUTOCHECKBOX | WS_TABSTOP,15,223,128,10')
    $l.Add('    GROUPBOX        "' + (Get-Text 'idd_words.actions' $language) + '",IDC_STATIC,287,220,70,55')
    $l.Add('    GROUPBOX        "' + (Get-Text 'idd_words.selection' $language) + '",IDC_STATIC,14,237,250,37')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_words.deselect' $language) + '",IDC_BUTTON_DESEL,138,251,50,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_words.remove_replacement' $language) + '",IDC_BUTTON_REMOVEHLREPL,197,251,55,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_words.add_to_exclusions' $language) + '",IDC_BUTTON_ADDHLTOEXCLS,21,251,51,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_words.select_all' $language) + '",IDC_BUTTON_SELALL,133,221,51,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_words.set_replacement' $language) + '",IDC_BUTTON_SETHLREPL,77,251,53,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_words.select_all_replacements' $language) + '",IDC_BUTTON_SELALLREPL,192,221,61,14')
    $l.Add('    GROUPBOX        "' + (Get-Text 'idd_words.current_word' $language) + '",IDC_WORDS_FR_GBOX_CURWORD,14,282,343,34')
    $l.Add('    EDITTEXT        IDC_WORDS_FR_EDIT_WORD,46,296,67,14,ES_AUTOHSCROLL | ES_READONLY')
    $l.Add('    EDITTEXT        IDC_WORDS_FR_EDIT_REPL,154,296,67,14,ES_AUTOHSCROLL | ES_READONLY')
    $l.Add('    LTEXT           "' + (Get-Text 'idd_words.word' $language) + '",IDC_WORDS_FR_TEXT_WORD,19,298,26,8')
    $l.Add('    LTEXT           "' + (Get-Text 'idd_words.replacement' $language) + '",IDC_WORDS_FR_TEXT_REPL,124,298,29,8')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_words.find' $language) + '",IDC_WORDS_FR_BTN_FIND,245,296,42,14')
    $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_words.replace' $language) + '",IDC_WORDS_FR_BTN_REPL,299,296,43,14,WS_DISABLED')
    $l.Add("END")
    $l.Add("")
    if ($language -eq "uk-UA") {
        $l.Add("IDD_SETTING_OTHER DIALOGEX 0, 0, 224, 242")
        $l.Add("STYLE DS_SETFONT | WS_CHILD | WS_SYSMENU")
        $l.Add('FONT 9, "Tahoma", 400, 0, 0xCC')
        $l.Add("BEGIN")
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.main_settings' $language) + '",IDC_STATIC,7,8,129,46')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_setting_other.encoding' $language) + '",IDC_STATIC,11,24,60,9')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_setting_other.keep_manual' $language) + '",IDC_KEEP,"Button",BS_AUTOCHECKBOX | BS_MULTILINE | WS_TABSTOP,12,37,119,15')
        $l.Add('    COMBOBOX        IDC_DEFAULT_ENC,51,21,79,30,CBS_DROPDOWNLIST | CBS_SORT | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.window_mode' $language) + '",IDC_STATIC,141,8,76,47')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_setting_other.restore_position' $language) + '",IDC_RESTORE_POS,"Button",BS_AUTOCHECKBOX | BS_MULTILINE | WS_TABSTOP,147,23,65,24')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.scripts_folder' $language) + '",IDC_STATIC,7,56,211,44')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_setting_other.default_scripts_folder' $language) + '",IDC_DEFAULT_SCRIPTS_FOLDER,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,11,68,80,10')
        $l.Add('    EDITTEXT        IDC_SCRIPTS_FOLDER_PATH,10,81,175,13,ES_AUTOHSCROLL')
        $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_setting_other.browse' $language) + '",IDC_SELECT_SCRIPTS_FOLDER_BUTTON,193,81,17,13')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.images' $language) + '",IDC_STATIC,7,102,116,33')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_setting_other.ask_image' $language) + '",IDC_SETTINGS_ASKIMAGE,')
        $l.Add('                    "Button",BS_AUTOCHECKBOX | BS_MULTILINE | WS_TABSTOP,13,113,103,17')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.thumbnails' $language) + '",IDC_STATIC,127,102,91,33')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_setting_other.clear_images' $language) + '",IDC_OPTIONS_CLEARIMGS,"Button",BS_AUTOCHECKBOX | BS_MULTILINE | WS_TABSTOP,136,112,74,18')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.nbsp' $language) + '",IDC_STATIC,7,171,89,45')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_setting_other.nbsp_char' $language) + '",IDC_STATIC,13,188,43,18')
        $l.Add('    COMBOBOX        IDC_NBSP_CHAR,63,191,27,30,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.keyboard' $language) + '",IDC_STATIC,101,171,116,45')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_setting_other.change_keyboard' $language) + '",IDC_CHANGE_KEYB,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,107,183,84,8')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.image_settings' $language) + '",IDC_STATIC,7,138,211,30')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_setting_other.format' $language) + '",IDC_STATIC,13,152,28,8')
        $l.Add('    COMBOBOX        IDC_IMAGETYPE,60,150,40,30,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    EDITTEXT        IDC_JPEGQUALITY,179,149,26,13,ES_AUTOHSCROLL | ES_NUMBER')
        $l.Add('    CONTROL         "",IDC_JPEGSPIN,"msctls_updown32",UDS_SETBUDDYINT | UDS_ALIGNRIGHT | UDS_AUTOBUDDY | UDS_ARROWKEYS | UDS_NOTHOUSANDS,204,149,7,14')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_setting_other.jpeg_quality' $language) + '",IDC_STATIC,129,152,43,8')
        $l.Add('    COMBOBOX        IDC_KEYB_LAYOUT,144,198,68,30,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_setting_other.layout' $language) + '",IDC_STATIC,107,200,34,8')
        $l.Add("END")
    } else {
        $l.Add("IDD_SETTING_OTHER DIALOGEX 0, 0, 231, 226")
        $l.Add("STYLE DS_SETFONT | WS_CHILD | WS_SYSMENU")
        $l.Add('FONT 9, "Tahoma", 400, 0, 0xCC')
        $l.Add("BEGIN")
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.main_settings' $language) + '",IDC_STATIC,6,11,124,46')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_setting_other.encoding' $language) + '",IDC_STATIC,11,23,60,9')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_setting_other.keep_manual' $language) + '",IDC_KEEP,"Button",BS_AUTOCHECKBOX | BS_MULTILINE | WS_TABSTOP,10,37,110,18')
        $l.Add('    COMBOBOX        IDC_DEFAULT_ENC,57,21,69,30,CBS_DROPDOWNLIST | CBS_SORT | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.window_mode' $language) + '",IDC_STATIC,134,11,85,47')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_setting_other.restore_position' $language) + '",IDC_RESTORE_POS,"Button",BS_AUTOCHECKBOX | BS_MULTILINE | WS_TABSTOP,144,25,69,24')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.scripts_folder' $language) + '",IDC_STATIC,6,60,213,42')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_setting_other.default_scripts_folder' $language) + '",IDC_DEFAULT_SCRIPTS_FOLDER,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,11,70,80,10')
        $l.Add('    EDITTEXT        IDC_SCRIPTS_FOLDER_PATH,10,82,170,13,ES_AUTOHSCROLL')
        $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_setting_other.browse' $language) + '",IDC_SELECT_SCRIPTS_FOLDER_BUTTON,194,82,17,13')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.images' $language) + '",IDC_STATIC,6,104,116,33')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_setting_other.ask_image' $language) + '",IDC_SETTINGS_ASKIMAGE,')
        $l.Add('                    "Button",BS_AUTOCHECKBOX | BS_VCENTER | BS_MULTILINE | WS_TABSTOP,15,115,99,17')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.thumbnails' $language) + '",IDC_STATIC,126,104,93,33')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_setting_other.clear_images' $language) + '",IDC_OPTIONS_CLEARIMGS,')
        $l.Add('                    "Button",BS_AUTOCHECKBOX | BS_MULTILINE | WS_TABSTOP,133,116,76,16')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.nbsp' $language) + '",IDC_STATIC,6,173,84,44')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_setting_other.nbsp_char' $language) + '",IDC_STATIC,12,190,47,19')
        $l.Add('    COMBOBOX        IDC_NBSP_CHAR,59,193,27,30,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.keyboard' $language) + '",IDC_STATIC,94,173,125,44')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_setting_other.change_keyboard' $language) + '",IDC_CHANGE_KEYB,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,100,185,76,8')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_setting_other.image_settings' $language) + '",IDC_STATIC,6,139,213,32')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_setting_other.format' $language) + '",IDC_STATIC,14,154,28,8')
        $l.Add('    COMBOBOX        IDC_IMAGETYPE,59,152,40,30,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    EDITTEXT        IDC_JPEGQUALITY,180,151,26,13,ES_AUTOHSCROLL | ES_NUMBER')
        $l.Add('    CONTROL         "",IDC_JPEGSPIN,"msctls_updown32",UDS_SETBUDDYINT | UDS_ALIGNRIGHT | UDS_AUTOBUDDY | UDS_ARROWKEYS | UDS_NOTHOUSANDS,205,151,7,14')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_setting_other.jpeg_quality' $language) + '",IDC_STATIC,119,154,51,8')
        $l.Add('    COMBOBOX        IDC_KEYB_LAYOUT,141,198,73,30,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_setting_other.layout' $language) + '",IDC_STATIC,101,200,37,8')
        $l.Add("END")
    }
    $l.Add("")
    if ($language -eq "uk-UA") {
        $l.Add("IDD_OPTIONS DIALOGEX 0, 0, 266, 219")
        $l.Add("STYLE DS_SETFONT | WS_CHILD | WS_SYSMENU")
        $l.Add('FONT 9, "Tahoma", 0, 0, 0x0')
        $l.Add("BEGIN")
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.foreground_color' $language) + '",IDC_OPTIONS_FOREGROUND_COLOR,13,66,44,8')
        $l.Add('    PUSHBUTTON      "",IDC_FG,60,64,20,12')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.background_color' $language) + '",IDC_OPTIONS_BACKGROUND_COLOR,85,66,35,8')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.font' $language) + '",IDC_OPTIONS_BODY_FONT,13,49,41,8')
        $l.Add('    COMBOBOX        IDC_FONT,47,47,207,70,CBS_DROPDOWNLIST | CBS_SORT | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.font_size' $language) + '",IDC_OPTIONS_FONT_SIZE,171,21,52,8')
        $l.Add('    COMBOBOX        IDC_FONT_SIZE,224,19,36,70,CBS_DROPDOWN | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_options.interface' $language) + '",IDC_OPTIONS_INTERFACE_GROUP,7,7,252,30')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_options.font_group' $language) + '",IDC_OPTIONS_BODY_GROUP,7,37,252,43')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_options.source_view' $language) + '",IDC_OPTIONS_SOURCE_GROUP,7,80,252,79')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.wrap_lines' $language) + '",IDC_WRAP,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,13,109,65,10')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.syntax_highlight' $language) + '",IDC_SYNTAXHL,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,13,125,80,10')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.show_eol' $language) + '",IDC_SHOWEOL,"Button",BS_AUTOCHECKBOX | BS_MULTILINE | WS_TABSTOP,13,138,86,16')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.fast_mode' $language) + '",IDC_FAST_MODE,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,148,66,63,10')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.language' $language) + '",IDC_OPTIONS_LANGUAGE_LABEL,13,22,41,8')
        $l.Add('    COMBOBOX        IDC_LANG,47,19,120,30,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_options.spell_checking' $language) + '",IDC_OPTIONS_SPELLCHECK_GROUP,7,165,252,48')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.background_spell_check' $language) + '",IDC_BACKGROUNDSPELLCHECK,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,124,177,77,10')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.use_spellchecker' $language) + '",IDC_USESPELLCHECKER,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,15,174,98,14')
        $l.Add('    EDITTEXT        IDC_CUSTOM_DICT,70,194,170,12,ES_AUTOHSCROLL')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.custom_dict' $language) + '",IDS_SPELL_CUSTOM_DICT,15,190,44,16')
        $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_options.dict_browse' $language) + '",IDC_DICTPATH,244,194,12,12')
        $l.Add('    PUSHBUTTON      "",IDC_BG,120,64,20,12')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.show_line_numbers' $language) + '",IDC_SHOWLINENUMBERS,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,111,125,96,11')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.tag_highlight' $language) + '",IDC_TAGHL,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,111,141,93,11')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.source_font' $language) + '",IDC_OPTIONS_SOURCE_FONT,13,94,41,8')
        $l.Add('    COMBOBOX        IDC_SRCFONT,47,92,207,70,CBS_DROPDOWNLIST | CBS_SORT | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.show_whitespace' $language) + '",IDC_SHOWWHITESPACE,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,111,109,82,11')
        $l.Add("END")
    } else {
        $l.Add("IDD_OPTIONS DIALOGEX 0, 0, 266, 233")
        $l.Add("STYLE DS_SETFONT | WS_CHILD | WS_SYSMENU")
        $l.Add('FONT 9, "Tahoma", 0, 0, 0x0')
        $l.Add("BEGIN")
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.foreground_color' $language) + '",IDC_OPTIONS_FOREGROUND_COLOR,13,66,42,8')
        $l.Add('    PUSHBUTTON      "",IDC_FG,57,64,20,12')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.background_color' $language) + '",IDC_OPTIONS_BACKGROUND_COLOR,82,66,37,8')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.font' $language) + '",IDC_OPTIONS_BODY_FONT,13,49,42,8')
        $l.Add('    COMBOBOX        IDC_FONT,48,47,206,70,CBS_DROPDOWNLIST | CBS_SORT | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.font_size' $language) + '",IDC_OPTIONS_FONT_SIZE,171,21,53,8')
        $l.Add('    COMBOBOX        IDC_FONT_SIZE,227,18,33,70,CBS_DROPDOWN | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_options.interface' $language) + '",IDC_OPTIONS_INTERFACE_GROUP,7,9,251,28')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_options.font_group' $language) + '",IDC_OPTIONS_BODY_GROUP,7,37,251,45')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_options.source_view' $language) + '",IDC_OPTIONS_SOURCE_GROUP,7,82,251,84')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.wrap_lines' $language) + '",IDC_WRAP,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,13,116,63,10')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.syntax_highlight' $language) + '",IDC_SYNTAXHL,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,13,132,84,10')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.show_eol' $language) + '",IDC_SHOWEOL,"Button",BS_AUTOCHECKBOX | BS_MULTILINE | WS_TABSTOP,13,145,96,17')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.fast_mode' $language) + '",IDC_FAST_MODE,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,148,66,62,10')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.language' $language) + '",IDC_OPTIONS_LANGUAGE_LABEL,14,21,24,8')
        $l.Add('    COMBOBOX        IDC_LANG,49,18,120,30,CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    GROUPBOX        "' + (Get-Text 'idd_options.spell_checking' $language) + '",IDC_OPTIONS_SPELLCHECK_GROUP,7,168,251,53')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.background_spell_check' $language) + '",IDC_BACKGROUNDSPELLCHECK,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,124,183,77,10')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.use_spellchecker' $language) + '",IDC_USESPELLCHECKER,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,15,180,98,14')
        $l.Add('    EDITTEXT        IDC_CUSTOM_DICT,83,201,156,12,ES_AUTOHSCROLL')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.custom_dict' $language) + '",IDS_SPELL_CUSTOM_DICT,15,198,61,15')
        $l.Add('    PUSHBUTTON      "' + (Get-Text 'idd_options.dict_browse' $language) + '",IDC_DICTPATH,244,201,12,12')
        $l.Add('    PUSHBUTTON      "",IDC_BG,122,64,20,12')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.show_line_numbers' $language) + '",IDC_SHOWLINENUMBERS,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,113,132,95,11')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.tag_highlight' $language) + '",IDC_TAGHL,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,113,147,93,11')
        $l.Add('    LTEXT           "' + (Get-Text 'idd_options.source_font' $language) + '",IDC_OPTIONS_SOURCE_FONT,13,99,42,8')
        $l.Add('    COMBOBOX        IDC_SRCFONT,48,97,206,70,CBS_DROPDOWNLIST | CBS_SORT | WS_VSCROLL | WS_TABSTOP')
        $l.Add('    CONTROL         "' + (Get-Text 'idd_options.show_whitespace' $language) + '",IDC_SHOWWHITESPACE,"Button",BS_AUTOCHECKBOX | WS_TABSTOP,113,116,82,11')
        $l.Add("END")
    }
    $l.Add("")
    $out=$outputByLanguage[$language]
    [IO.File]::WriteAllText($out,($l -join "`r`n"),$utf16LeBom)
    Write-Host "Малые диалоги FBE сгенерированы."
    Write-Host "  Язык: $language"
    Write-Host "  Файл: $out"
}
