#pragma once
#include "../version.h"

#define IDI_IMPORT_EPUB 101
#define IDI_IMPORTEPUBBATCH     102

#define IDS_IMPORT_OPTIONS_TITLE 200
#define IDS_IMPORT_OPTIONS_HEADER 201
#define IDS_IMPORT_OPTIONS_SVG_LABEL 202
#define IDS_IMPORT_OPTIONS_SVG_KEEP 203
#define IDS_IMPORT_OPTIONS_SVG_PNG 204
#define IDS_IMPORT_OPTIONS_SVG_JPEG 205
#define IDS_IMPORT_OPTIONS_SVG_SKIP 206
#define IDS_IMPORT_OPTIONS_HINT 207
#define IDS_IMPORT_OPTIONS_BUTTON_DEFAULTS 208
#define IDS_IMPORT_OPTIONS_BUTTON_OK 209
#define IDS_IMPORT_OPTIONS_BUTTON_CANCEL 210
#define IDS_IMPORT_OPTIONS_TOOLTIP_SVG_LABEL 211
#define IDS_IMPORT_OPTIONS_TOOLTIP_SVG_COMBO 212
#define IDS_IMPORT_OPTIONS_TOOLTIP_DEFAULTS 213

#define IDS_IMPORT_OPTIONS_OPT_COVER 220
#define IDS_IMPORT_OPTIONS_TT_COVER 221
#define IDS_IMPORT_OPTIONS_OPT_IMAGES 222
#define IDS_IMPORT_OPTIONS_TT_IMAGES 223
#define IDS_IMPORT_OPTIONS_OPT_NOTES 224
#define IDS_IMPORT_OPTIONS_TT_NOTES 225
#define IDS_IMPORT_OPTIONS_OPT_NAV_TITLES 226
#define IDS_IMPORT_OPTIONS_TT_NAV_TITLES 227
#define IDS_IMPORT_OPTIONS_OPT_REPAIR_ENCODING 228
#define IDS_IMPORT_OPTIONS_TT_REPAIR_ENCODING 229
#define IDS_IMPORT_OPTIONS_OPT_SKIP_SERVICE 230
#define IDS_IMPORT_OPTIONS_TT_SKIP_SERVICE 231
#define IDS_IMPORT_OPTIONS_OPT_TABLES 232
#define IDS_IMPORT_OPTIONS_TT_TABLES 233
#define IDS_IMPORT_OPTIONS_OPT_LISTS 234
#define IDS_IMPORT_OPTIONS_TT_LISTS 235
#define IDS_IMPORT_OPTIONS_OPT_POEMS 236
#define IDS_IMPORT_OPTIONS_TT_POEMS 237
#define IDS_IMPORT_OPTIONS_OPT_SUBTITLES 238
#define IDS_IMPORT_OPTIONS_TT_SUBTITLES 239
#define IDS_IMPORT_OPTIONS_OPT_SPLIT_HEADINGS 240
#define IDS_IMPORT_OPTIONS_TT_SPLIT_HEADINGS 241
#define IDS_IMPORT_OPTIONS_OPT_LINKS 242
#define IDS_IMPORT_OPTIONS_TT_LINKS 243
#define IDS_IMPORT_OPTIONS_OPT_CLEAN_TYPOGRAPHY 244
#define IDS_IMPORT_OPTIONS_TT_CLEAN_TYPOGRAPHY 245
#define IDS_IMPORT_OPTIONS_OPT_PAGE_BREAKS 246
#define IDS_IMPORT_OPTIONS_TT_PAGE_BREAKS 247
#define IDS_IMPORT_OPTIONS_OPT_SKIP_HIDDEN 248
#define IDS_IMPORT_OPTIONS_TT_SKIP_HIDDEN 249
#define IDS_IMPORT_OPTIONS_OPT_VALIDATE 250
#define IDS_IMPORT_OPTIONS_TT_VALIDATE 251
#define IDS_IMPORT_OPTIONS_OPT_DIAGNOSTIC 252
#define IDS_IMPORT_OPTIONS_TT_DIAGNOSTIC 253
#define IDS_IMPORT_OPTIONS_OPT_LOG 254
#define IDS_IMPORT_OPTIONS_TT_LOG 255
#define IDS_IMPORT_OPTIONS_OPT_SAVE_FB2 256
#define IDS_IMPORT_OPTIONS_TT_SAVE_FB2 257
#define IDS_IMPORT_OPTIONS_OPT_CSS_SEMANTICS 258
#define IDS_IMPORT_OPTIONS_TT_CSS_SEMANTICS 259
#define IDS_IMPORT_OPTIONS_OPT_REMOVE_BACKLINKS 260
#define IDS_IMPORT_OPTIONS_TT_REMOVE_BACKLINKS 261
#define IDS_IMPORT_OPTIONS_OPT_REMOVE_SERVICE_SECTIONS 262
#define IDS_IMPORT_OPTIONS_TT_REMOVE_SERVICE_SECTIONS 263
#define IDS_IMPORT_OPTIONS_OPT_LOG_ON_WARNINGS 264
#define IDS_IMPORT_OPTIONS_TT_LOG_ON_WARNINGS 265
#define IDS_IMPORT_OPTIONS_OPT_SAVE_INTERMEDIATE_ON_ERROR 266
#define IDS_IMPORT_OPTIONS_TT_SAVE_INTERMEDIATE_ON_ERROR 267
#define IDS_IMPORT_OPTIONS_OPT_KEEP_TEMP 268
#define IDS_IMPORT_OPTIONS_TT_KEEP_TEMP 269

#define IDS_IMPORT_OPTIONS_GROUP_CONTENT 280
#define IDS_IMPORT_OPTIONS_TT_GROUP_CONTENT 281
#define IDS_IMPORT_OPTIONS_GROUP_IMAGES 282
#define IDS_IMPORT_OPTIONS_TT_GROUP_IMAGES 283
#define IDS_IMPORT_OPTIONS_GROUP_LINKS_NOTES 284
#define IDS_IMPORT_OPTIONS_TT_GROUP_LINKS_NOTES 285
#define IDS_IMPORT_OPTIONS_GROUP_CLEANUP 286
#define IDS_IMPORT_OPTIONS_TT_GROUP_CLEANUP 287
#define IDS_IMPORT_OPTIONS_GROUP_DIAGNOSTICS 288
#define IDS_IMPORT_OPTIONS_TT_GROUP_DIAGNOSTICS 289

#define IDS_IMPORT_PLUGIN_FILEDLG_TITLE 300
#define IDS_IMPORT_PLUGIN_FILEDLG_OPEN_BUTTON 301
#define IDS_IMPORT_PLUGIN_FILEDLG_FILE_LABEL 302
#define IDS_IMPORT_PLUGIN_FILEDLG_SETTINGS_BUTTON 303
#define IDS_IMPORT_PLUGIN_ERROR_MSXML_CREATE 304
#define IDS_IMPORT_PLUGIN_ERROR_MSXML_LOAD 305
#define IDS_IMPORT_PLUGIN_STAGE_PREPARE 306
#define IDS_IMPORT_PLUGIN_STAGE_READ_SETTINGS 307
#define IDS_IMPORT_PLUGIN_STAGE_SELECT_FILE 308
#define IDS_IMPORT_PLUGIN_STAGE_CONVERT 309
#define IDS_IMPORT_PLUGIN_STAGE_CREATE_DOM 310
#define IDS_IMPORT_PLUGIN_STAGE_RETURN_RESULT 311
#define IDS_IMPORT_PLUGIN_WARNING_PARTIAL_IMPORT 312
#define IDS_IMPORT_PLUGIN_ERROR_COM 313
#define IDS_IMPORT_PLUGIN_ERROR_UNEXPECTED 314


#define IDS_IMPORT_RUNTIME_XML_UNKNOWN_AFTER_HTML 400
#define IDS_IMPORT_RUNTIME_XML_UNKNOWN_AFTER_XML 401
#define IDS_IMPORT_RUNTIME_HTML_FALLBACK_FAILED 402
#define IDS_IMPORT_RUNTIME_XML_FALLBACK_FAILED 403
#define IDS_IMPORT_RUNTIME_ZIP_UNSAFE_PATH 404
#define IDS_IMPORT_RUNTIME_ZIP_REPARSE_POINT 405
#define IDS_IMPORT_RUNTIME_ZIP_TIMEOUT_CONTAINER 406
#define IDS_IMPORT_RUNTIME_ZIP_COPY_FAILED 407
#define IDS_IMPORT_RUNTIME_ZIP_SHELL_CREATE_FAILED 408
#define IDS_IMPORT_RUNTIME_ZIP_OPEN_FAILED 409
#define IDS_IMPORT_RUNTIME_ZIP_DEST_FAILED 410
#define IDS_IMPORT_RUNTIME_ZIP_ITEMS_FAILED 411
#define IDS_IMPORT_RUNTIME_ZIP_ITEMS_DISPATCH_FAILED 412
#define IDS_IMPORT_RUNTIME_ZIP_EXTRACT_FAILED 413
#define IDS_IMPORT_RUNTIME_MSXML_CREATE_FAILED 414
#define IDS_IMPORT_RUNTIME_XML_UNKNOWN 415
#define IDS_IMPORT_RUNTIME_XML_LOAD_FAILED 416
#define IDS_IMPORT_RUNTIME_CONTAINER_MISSING 417
#define IDS_IMPORT_RUNTIME_CONTAINER_ROOTFILE_MISSING 418
#define IDS_IMPORT_RUNTIME_OPF_SPINE_MISSING 419
#define IDS_IMPORT_RUNTIME_NAV_READ_FAILED 420
#define IDS_IMPORT_RUNTIME_NAV_HEADINGS_COUNT 421
#define IDS_IMPORT_RUNTIME_NCX_READ_FAILED 422
#define IDS_IMPORT_RUNTIME_NCX_NAVPOINT_COUNT 423
#define IDS_IMPORT_RUNTIME_SELECTED_EPUB_MISSING 424
#define IDS_IMPORT_RUNTIME_SPINE_FILE_MISSING 425
#define IDS_IMPORT_RUNTIME_SPINE_NO_SUPPORTED 426
#define IDS_IMPORT_RUNTIME_IMAGE_PLACEHOLDER_OPEN 427
#define IDS_IMPORT_RUNTIME_IMAGE_PLACEHOLDER 428
#define IDS_IMPORT_RUNTIME_DEDICATION_TITLE 429
#define IDS_IMPORT_RUNTIME_EMPTY_NOTE_PLACEHOLDER 430
#define IDS_IMPORT_RUNTIME_CHAPTER_TEXT_NOT_EXTRACTED 431
#define IDS_IMPORT_RUNTIME_IMPORT_WARNINGS_TITLE 432
#define IDS_IMPORT_RUNTIME_SVG_ADAPTER_MISSING 433
#define IDS_IMPORT_RUNTIME_SVG_ADAPTER_LOAD_FAILED 434
#define IDS_IMPORT_RUNTIME_SVG_ADAPTER_EXPORT_MISSING 435
#define IDS_IMPORT_RUNTIME_SVG_ADAPTER_RENDER_FAILED 436
#define IDS_IMPORT_RUNTIME_SVG_PLACEHOLDER_SUFFIX 437
#define IDS_IMPORT_RUNTIME_GDIPLUS_PNG_TO_JPEG_FAILED 438
#define IDS_IMPORT_RUNTIME_SVG_SAVE_JPEG_FAILED 439
#define IDS_IMPORT_RUNTIME_GDIPLUS_PLACEHOLDER_FAILED 440
#define IDS_IMPORT_RUNTIME_SVG_PLACEHOLDER_CREATE_FAILED 441
#define IDS_IMPORT_RUNTIME_SVG_SKIPPED_BY_OPTION 442
#define IDS_IMPORT_RUNTIME_SVG_PLACEHOLDER_REASON 443
#define IDS_IMPORT_RUNTIME_SVG_CONVERTED_READ_FAILED 444
#define IDS_IMPORT_RUNTIME_XHTML_NOTES_CHECK_FAILED 445
#define IDS_IMPORT_RUNTIME_SVG_SPINE_SKIPPED 446
#define IDS_IMPORT_RUNTIME_SPINE_IMAGE_MISSING 447
#define IDS_IMPORT_RUNTIME_XHTML_READ_FAILED 448
#define IDS_IMPORT_RUNTIME_XHTML_BODY_MISSING 449
#define IDS_IMPORT_RUNTIME_NOTES_BODY_MOVED 450
#define IDS_IMPORT_RUNTIME_IMAGE_PREPARE_FAILED 451
#define IDS_IMPORT_RUNTIME_MIMETYPE_MISSING 452
#define IDS_IMPORT_RUNTIME_MIMETYPE_UNEXPECTED 453
#define IDS_IMPORT_RUNTIME_ENCRYPTION_DETECTED 454
#define IDS_IMPORT_RUNTIME_IMAGE_BINARY_MISSING 455
#define IDS_IMPORT_RUNTIME_DUPLICATE_FB2_ID 456
#define IDS_IMPORT_RUNTIME_INTERNAL_LINK_MISSING_ID 457
#define IDS_IMPORT_RUNTIME_NOTE_SECTION_MISSING 458
#define IDS_IMPORT_RUNTIME_FINAL_MSXML_CREATE_FAILED 459
#define IDS_IMPORT_RUNTIME_FINAL_XML_FAILED 460
#define IDS_IMPORT_RUNTIME_FINAL_BODY_MISSING 461

// Resource identifier required by Windows shell to display VersionInfo.
// Without this define, VS_VERSION_INFO in .rc can become a named resource
// instead of RT_VERSION resource #1, and Explorer will not show file details.
#ifndef VS_VERSION_INFO
#define VS_VERSION_INFO 1
#endif


// Версия плагина.
// Если в проекте FBE есть общий version.h и нужно использовать общую версию,
// эти макросы можно переопределить через настройки Resource Compiler.
#ifndef FBE_VERSION_NUMBER
#define FBE_VERSION_NUMBER 1,0,72,0
#endif

#ifndef FBE_VERSION_STRING
#define FBE_VERSION_STRING "1.0.72.0"
#endif

// -----------------------------------------------------------------------------
// Version resource strings.
// Keep DLL and batch utility metadata separate so Explorer and diagnostics show
// the correct file identity for each binary.
// -----------------------------------------------------------------------------
#define IMEPUB_DLL_FILE_DESCRIPTION      "FictionBook Editor EPUB import plugin"
#define IMEPUB_DLL_INTERNAL_NAME         "ImportEPUB"
#define IMEPUB_DLL_ORIGINAL_FILENAME     "ImportEPUB.dll"
#define IMEPUB_DLL_PRODUCT_NAME          "FictionBook Editor EPUB import plugin"

#define IMEPUB_BATCH_FILE_DESCRIPTION    "FictionBook Editor EPUB batch import utility"
#define IMEPUB_BATCH_INTERNAL_NAME       "ImportEPUBBatch"
#define IMEPUB_BATCH_ORIGINAL_FILENAME   "ImportEPUBBatch.exe"
#define IMEPUB_BATCH_PRODUCT_NAME        "FictionBook Editor EPUB batch import utility"

#define IMEPUB_LUNASVG_FILE_DESCRIPTION  "FictionBook Editor EPUB SVG cover converter"
#define IMEPUB_LUNASVG_INTERNAL_NAME     "ImportEPUBLunaSVG"
#define IMEPUB_LUNASVG_ORIGINAL_FILENAME "ImportEPUBLunaSVG.dll"
#define IMEPUB_LUNASVG_PRODUCT_NAME      "FictionBook Editor EPUB import plugin"

#define IMEPUB_COMPANY_NAME              "sklart"
#define IMEPUB_LEGAL_COPYRIGHT           "Copyright 2026 Artem Sklyarov aka sklart"
