#pragma once

const DWORD FBE_INTERFACE_LANGUAGE_AUTO = 0;
const DWORD FBE_INTERFACE_LANGUAGE_ENGLISH = 0xFBE001;
const DWORD FBE_INTERFACE_LANGUAGE_RUSSIAN = 0xFBE002;
const DWORD FBE_INTERFACE_LANGUAGE_UKRAINIAN = 0xFBE003;
const DWORD FBE_INTERFACE_LANGUAGE_GERMAN = 0xFBE004;
const DWORD FBE_INTERFACE_LANGUAGE_FRENCH = 0xFBE005;
const DWORD FBE_INTERFACE_LANGUAGE_SPANISH = 0xFBE006;
const DWORD FBE_INTERFACE_LANGUAGE_ITALIAN = 0xFBE007;
const DWORD FBE_INTERFACE_LANGUAGE_POLISH = 0xFBE008;
const DWORD FBE_INTERFACE_LANGUAGE_PORTUGUESE = 0xFBE009;
const DWORD FBE_INTERFACE_LANGUAGE_DUTCH = 0xFBE00A;
const DWORD FBE_INTERFACE_LANGUAGE_CZECH = 0xFBE00B;
const DWORD FBE_INTERFACE_LANGUAGE_BULGARIAN = 0xFBE00C;

enum class GenreCatalog
{
	Standard,
	Librusec,
};
