; license 
LicenseLangString License ${LANG_ENGLISH} "${INPUTDIR}\LICENSE"

; components section strings
LangString Main ${LANG_ENGLISH} "Program files"
LangString System_Integration ${LANG_ENGLISH} "System integration"
LangString FB2_File_Association ${LANG_ENGLISH} "Use FBE Next for .fb2 files"
LangString FBD_File_Association ${LANG_ENGLISH} "Use FBE Next for .fbd description files"
LangString FB2_Validate_Command ${LANG_ENGLISH} "Add “Check FB2 for errors” command"
LangString FB2_Explorer_Properties ${LANG_ENGLISH} ".fb2 properties and thumbnails in Explorer"
LangString ShCutGroup ${LANG_ENGLISH} "Shortcuts"
LangString Desktop_ShortCut ${LANG_ENGLISH} "Desktop"
LangString Start_Menu_ShortCuts ${LANG_ENGLISH} "Start menu"
LangString PluginsGroup ${LANG_ENGLISH} "Plugins"
LangString ImportPluginsGroup ${LANG_ENGLISH} "Import plugins"
LangString ExportPluginsGroup ${LANG_ENGLISH} "Export plugins"
LangString Plugin_ImportEPUB ${LANG_ENGLISH} "Import EPUB"
LangString Plugin_ImportEPUB_SVG ${LANG_ENGLISH} "SVG covers for ImportEPUB"
LangString Plugin_ExportHTML ${LANG_ENGLISH} "Export HTML"
LangString Plugin_ExportDOCX ${LANG_ENGLISH} "Export DOCX"
LangString Plugin_ExportEPUB ${LANG_ENGLISH} "Export EPUB"
LangString Plugin_BatchConverters ${LANG_ENGLISH} "Batch converters"
LangString Scripts ${LANG_ENGLISH} "Scripts"
LangString Dictionaries ${LANG_ENGLISH} "Dictionaries"
LangString LanguagePacksGroup ${LANG_ENGLISH} "Interface languages"

LangString EnglishDict ${LANG_ENGLISH} "English"
LangString RussianDict ${LANG_ENGLISH} "Russian"
LangString UkrainianDict ${LANG_ENGLISH} "Ukrainian"
LangString ByelorussianDict ${LANG_ENGLISH} "Byelorussian"
LangString BulgarianDict ${LANG_ENGLISH} "Bulgarian"
LangString CzechDict ${LANG_ENGLISH} "Czech"
LangString PolishDict ${LANG_ENGLISH} "Polish"
LangString GermanDict ${LANG_ENGLISH} "German"
LangString FrenchDict ${LANG_ENGLISH} "French"
LangString SpanishDict ${LANG_ENGLISH} "Spanish"
LangString ItalianDict ${LANG_ENGLISH} "Italian"
LangString DownloadingDict ${LANG_ENGLISH} "Downloading "
LangString Dictionary ${LANG_ENGLISH} " dictionary"

; components descriptions
LangString DESC_Main ${LANG_ENGLISH} "FBE application files and libraries."
LangString DESC_System_Integration ${LANG_ENGLISH} "Optional .fb2 integration with Windows."
LangString DESC_FB2_File_Association ${LANG_ENGLISH} "Opens .fb2 files in FBE Next and changes their icon."
LangString DESC_FBD_File_Association ${LANG_ENGLISH} "Opens .fbd description files in FBE Next and changes their icon."
LangString DESC_FB2_Validate_Command ${LANG_ENGLISH} "Adds a context-menu command to check .fb2 files with FBV."
LangString DESC_FB2_Explorer_Properties ${LANG_ENGLISH} "Adds .fb2 properties and cover thumbnails in Explorer. Requires administrator rights."
LangString DESC_ShCutGroup ${LANG_ENGLISH} "Install shortcuts."
LangString DESC_Desktop_ShortCut ${LANG_ENGLISH} "Desktop shortcut."
LangString DESC_Start_Menu_ShortCuts ${LANG_ENGLISH} "Start menu shortcuts."
LangString DESC_PluginsGroup ${LANG_ENGLISH} "Optional plugins that extend FBE."
LangString DESC_ImportPluginsGroup ${LANG_ENGLISH} "Plugins for importing external book formats."
LangString DESC_ExportPluginsGroup ${LANG_ENGLISH} "Plugins for exporting books and documents."
LangString DESC_Plugin_ImportEPUB ${LANG_ENGLISH} "Imports EPUB books into FBE."
LangString DESC_Plugin_ImportEPUB_SVG ${LANG_ENGLISH} "Converts SVG EPUB covers to PNG/JPEG."
LangString DESC_Plugin_ExportHTML ${LANG_ENGLISH} "Exports the current book to HTML."
LangString DESC_Plugin_ExportDOCX ${LANG_ENGLISH} "Exports the current book to DOCX."
LangString DESC_Plugin_ExportEPUB ${LANG_ENGLISH} "Exports the current book to EPUB."
LangString DESC_Plugin_BatchConverters ${LANG_ENGLISH} "Installs DOCX/EPUB batch-conversion utilities."
LangString DESC_Scripts ${LANG_ENGLISH} "Useful community scripts."
LangString DESC_Dictionaries ${LANG_ENGLISH} "Dictionaries for built-in spell-checker."
LangString DESC_LanguagePacksGroup ${LANG_ENGLISH} "Interface language resources. English is required; Russian and Ukrainian are selected."
LangString DESC_LanguagePack ${LANG_ENGLISH} "Installs interface translations and the localized Validate command. Dictionaries are separate."

; error messages
LangString ErrCheckMSXMLVersion ${LANG_ENGLISH} "This application requires Microsoft XML Parser version 4.0 to run."
LangString ErrCheckIEVersion ${LANG_ENGLISH} "This application requires Microsoft Internet Expolorer version 5.5 or newer to run."
LangString ErrCheckFBERunning ${LANG_ENGLISH} "Please exit FictionBook Editor before continue."
LangString ErrCheckFBVRunning ${LANG_ENGLISH} "Please exit FictionBook Validator before continue."
LangString ErrNTCurrentVersion ${LANG_ENGLISH} "FictionBook Tools run only on Windows NT and later OS'es."
LangString ErrShellIntergation ${LANG_ENGLISH} "FB shell intergation dll was in use and could not be overwritten.$\r$\n\
	Please logout and logon again, and restart this installation."
LangString WarnModernPropertyHandlerInstall ${LANG_ENGLISH} "Could not enable modern .fb2 properties in Windows Explorer automatically. The main FBE installation will continue, and the shell integration can be enabled later manually."
LangString UacRetryInstaller ${LANG_ENGLISH} "Administrator privileges are required to complete system integration. Retry elevation?"
LangString UacAbortInstaller ${LANG_ENGLISH} "System integration requires administrator privileges. Setup will be aborted."
LangString UacLogonServiceInstaller ${LANG_ENGLISH} "Could not request elevation because the logon service is unavailable."
LangString UacRetryUninstaller ${LANG_ENGLISH} "Administrator privileges are required to remove system integration correctly. Retry elevation?"
LangString UacAbortUninstaller ${LANG_ENGLISH} "Removing system integration requires administrator privileges. Uninstall will be aborted."
LangString UacLogonServiceUninstaller ${LANG_ENGLISH} "Could not request elevation for uninstall because the logon service is unavailable."
LangString UacUnknownError ${LANG_ENGLISH} "Could not elevate privileges. Error code:"
LangString FinishPageTitle ${LANG_ENGLISH} "Installation complete"
LangString FinishPageText ${LANG_ENGLISH} "FictionBook Editor Next has been installed successfully.$\r$\n$\r$\nClick $\"Finish$\" to close Setup."
LangString FinishPageRunText ${LANG_ENGLISH} "Run FictionBook Editor Next"

; uninstall messages
LangString UninstAskSettings ${LANG_ENGLISH} "Would you like to delete all application settings?"
