; license 
LangString FBD_File_Association ${LANG_UKRAINIAN} "Використовувати FBE Next для файлів опису .fbd"
LangString DESC_FBD_File_Association ${LANG_UKRAINIAN} "Відкриває файли опису .fbd у FBE Next і змінює їхній значок."
LicenseLangString License ${LANG_UKRAINIAN} "${INPUTDIR}\gpl-3.0.ua.txt"

; components section strings
LangString Main ${LANG_UKRAINIAN} "Файли програми"
LangString DeploymentModeTitle ${LANG_UKRAINIAN} "Тип розгортання"
LangString DeploymentModeInstalled ${LANG_UKRAINIAN} "Встановити FictionBook Editor Next"
LangString DeploymentModePortable ${LANG_UKRAINIAN} "Створити портативну копію"
LangString InstallScopeTitle ${LANG_UKRAINIAN} "Область встановлення"
LangString InstallScopeCurrent ${LANG_UKRAINIAN} "Лише для поточного користувача"
LangString InstallScopeAllUsers ${LANG_UKRAINIAN} "Для всіх користувачів комп’ютера"
LangString InstallScopeConflict ${LANG_UKRAINIAN} "FictionBook Editor Next уже встановлено для іншої області користувачів. Спочатку видаліть або оновіть те встановлення, а потім знову запустіть цей інсталятор. Налаштування не буде видалено."
LangString System_Integration ${LANG_UKRAINIAN} "Системна інтеграція"
LangString FB2_File_Association ${LANG_UKRAINIAN} "Використовувати FBE Next для .fb2"
LangString FB2_Validate_Command ${LANG_UKRAINIAN} "Команда «Перевірити FB2 на помилки»"
LangString FB2_Explorer_Properties ${LANG_UKRAINIAN} "Властивості та мініатюри .fb2 у Провіднику"
LangString ShCutGroup ${LANG_UKRAINIAN} "Ярлики"
LangString Desktop_ShortCut ${LANG_UKRAINIAN} "Стільниця"
LangString Start_Menu_ShortCuts ${LANG_UKRAINIAN} "Меню «Пуск»"
LangString PluginsGroup ${LANG_UKRAINIAN} "Модулі"
LangString ImportPluginsGroup ${LANG_UKRAINIAN} "Плагіни імпорту"
LangString ExportPluginsGroup ${LANG_UKRAINIAN} "Плагіни експорту"
LangString Plugin_ImportEPUB ${LANG_UKRAINIAN} "Імпорт EPUB"
LangString Plugin_ImportEPUB_SVG ${LANG_UKRAINIAN} "SVG-обкладинки для ImportEPUB"
LangString Plugin_ExportHTML ${LANG_UKRAINIAN} "Експорт HTML"
LangString Plugin_ExportDOCX ${LANG_UKRAINIAN} "Експорт DOCX"
LangString Plugin_ExportEPUB ${LANG_UKRAINIAN} "Експорт EPUB"
LangString Plugin_BatchConverters ${LANG_UKRAINIAN} "Batch-конвертери"
LangString Scripts ${LANG_UKRAINIAN} "Скрипти"
LangString Dictionaries ${LANG_UKRAINIAN} "Словники"
LangString LanguagePacksGroup ${LANG_UKRAINIAN} "Мови інтерфейсу"

LangString EnglishDict ${LANG_UKRAINIAN} "англійський"
LangString RussianDict ${LANG_UKRAINIAN} "російський"
LangString UkrainianDict ${LANG_UKRAINIAN} "український"
LangString ByelorussianDict ${LANG_UKRAINIAN} "білоруський"
LangString BulgarianDict ${LANG_UKRAINIAN} "болгарський"
LangString CzechDict ${LANG_UKRAINIAN} "чеський"
LangString PolishDict ${LANG_UKRAINIAN} "польський"
LangString GermanDict ${LANG_UKRAINIAN} "німецький"
LangString FrenchDict ${LANG_UKRAINIAN} "французький"
LangString SpanishDict ${LANG_UKRAINIAN} "іспанський"
LangString ItalianDict ${LANG_UKRAINIAN} "італійський"
LangString DownloadingDict ${LANG_UKRAINIAN} "Завантажую "
LangString Dictionary ${LANG_UKRAINIAN} " словник"

; components descriptions
LangString DESC_Main ${LANG_UKRAINIAN} "Файли FBE, бібліотеки та службові дані."
LangString DESC_System_Integration ${LANG_UKRAINIAN} "Необов'язкова інтеграція .fb2 і .fbd з Windows."
LangString DESC_FB2_File_Association ${LANG_UKRAINIAN} "Відкриває .fb2 у FBE Next і змінює його значок."
LangString DESC_FB2_Validate_Command ${LANG_UKRAINIAN} "Додає команду перевірки .fb2 через FBV."
LangString DESC_FB2_Explorer_Properties ${LANG_UKRAINIAN} "Властивості й мініатюри .fb2 у Провіднику. Потрібні права адміністратора."
LangString DESC_ShCutGroup ${LANG_UKRAINIAN} "Встановити ярлики."
LangString DESC_Desktop_ShortCut ${LANG_UKRAINIAN} "Ярлик на Стільниці (Робочому столі)."
LangString DESC_Start_Menu_ShortCuts ${LANG_UKRAINIAN} "Ярлики в меню «Пуск»."
LangString DESC_PluginsGroup ${LANG_UKRAINIAN} "Додаткові плагіни для FBE."
LangString DESC_ImportPluginsGroup ${LANG_UKRAINIAN} "Імпорт книг із зовнішніх форматів."
LangString DESC_ExportPluginsGroup ${LANG_UKRAINIAN} "Експорт у зовнішні книжкові та документні формати."
LangString DESC_Plugin_ImportEPUB ${LANG_UKRAINIAN} "Імпортує EPUB-книги у FBE."
LangString DESC_Plugin_ImportEPUB_SVG ${LANG_UKRAINIAN} "Перетворює SVG-обкладинки EPUB у PNG/JPEG."
LangString DESC_Plugin_ExportHTML ${LANG_UKRAINIAN} "Експортує поточну книгу в HTML."
LangString DESC_Plugin_ExportDOCX ${LANG_UKRAINIAN} "Експортує поточну книгу в DOCX."
LangString DESC_Plugin_ExportEPUB ${LANG_UKRAINIAN} "Експортує поточну книгу в EPUB."
LangString DESC_Plugin_BatchConverters ${LANG_UKRAINIAN} "Утиліти пакетної конвертації DOCX/EPUB."
LangString DESC_Scripts ${LANG_UKRAINIAN} "Збірка корисних скриптів спільноти."
LangString DESC_Dictionaries ${LANG_UKRAINIAN} "Словники для перевірки орфографії."
LangString DESC_LanguagePacksGroup ${LANG_UKRAINIAN} "Ресурси мов інтерфейсу. Англійська обов'язкова; російська та українська вибрані."
LangString DESC_LanguagePack ${LANG_UKRAINIAN} "Переклади інтерфейсу й локалізована команда Validate. Словники вибираються окремо."

; error messages
LangString ErrCheckMSXMLVersion ${LANG_UKRAINIAN} "Для встановлення потрібен Microsoft XML Parser версії 4.0."
LangString ErrCheckIEVersion ${LANG_UKRAINIAN} "Для встановлення потрібен Microsoft Internet Expolorer версії 5.5 або новіший."
LangString ErrCheckFBERunning ${LANG_UKRAINIAN} "Перед початком встановлення закрийте FictionBook Editor."
LangString ErrCheckFBVRunning ${LANG_UKRAINIAN} "Перед початком встановлення закрийте FictionBook Validator."
LangString ErrNTCurrentVersion ${LANG_UKRAINIAN} "FictionBook Tools працює лише у Windows NT, XP, Vista, 7."
LangString ErrShellIntergation ${LANG_UKRAINIAN} "DLL-бібліотека інтеграції оболонки FB використовується і її неможливо перезаписати.$\r$\n\
	Будь ласка, завершіть сеанс, після чого перезапустіть встановлення."
LangString WarnModernPropertyHandlerInstall ${LANG_UKRAINIAN} "Не вдалося автоматично ввімкнути сучасні властивості .fb2 у Провіднику Windows. Основне встановлення FBE буде продовжено, а shell-інтеграцію можна буде ввімкнути пізніше вручну."
LangString UacRetryInstaller ${LANG_UKRAINIAN} "Для завершення встановлення системної інтеграції потрібні права адміністратора. Повторити запит на підвищення прав?"
LangString UacAbortInstaller ${LANG_UKRAINIAN} "Системна інтеграція потребує прав адміністратора. Встановлення буде перервано."
LangString UacLogonServiceInstaller ${LANG_UKRAINIAN} "Не вдалося запросити підвищення прав: служба входу в систему недоступна."
LangString UacRetryUninstaller ${LANG_UKRAINIAN} "Для коректного видалення системної інтеграції потрібні права адміністратора. Повторити запит на підвищення прав?"
LangString UacAbortUninstaller ${LANG_UKRAINIAN} "Видалення системної інтеграції потребує прав адміністратора. Деінсталяцію буде перервано."
LangString UacLogonServiceUninstaller ${LANG_UKRAINIAN} "Не вдалося запросити підвищення прав для деінсталяції: служба входу в систему недоступна."
LangString UacUnknownError ${LANG_UKRAINIAN} "Не вдалося підвищити права. Код помилки:"
LangString FinishPageTitle ${LANG_UKRAINIAN} "Встановлення завершено"
LangString FinishPageText ${LANG_UKRAINIAN} "FictionBook Editor Next успішно встановлено.$\r$\n$\r$\nНатисніть кнопку $\"Готово$\", щоб вийти з програми встановлення."
LangString FinishPageRunText ${LANG_UKRAINIAN} "Запустити FictionBook Editor Next"

; uninstall messages
LangString UninstAskSettings ${LANG_UKRAINIAN} "Бажаєте видалити файли налаштувань програми?"
